include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - submodules/**
    - lib/i18n/strings.g.dart
    - lib/objectbox.g.dart
    - backup/

linter:
  rules:
    use_super_parameters: true
    directives_ordering: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    always_declare_return_types: true
    avoid_return_types_on_setters: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    prefer_single_quotes: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: false
    unnecessary_breaks: true
    unnecessary_to_list_in_spreads: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_string_buffers: true
    curly_braces_in_flow_control_structures: false
    omit_obvious_property_types: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    avoid_final_parameters: true

    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

