import 'package:shared_preferences/shared_preferences.dart';

/// Service for managing Terms and Conditions acceptance
class TermsAndConditionsService {
  static const _termsAcceptedKey = 'termsAccepted';
  static const _termsAcceptedVersionKey = 'termsAcceptedVersion';
  static const _termsAcceptedDateKey = 'termsAcceptedDate';

  /// Current version of the terms and conditions
  /// Used for tracking when acceptance occurred.
  /// Version changes no longer force a blocking re-acceptance popup.
  static const currentTermsVersion = '0.10.1';

  /// Check if user has accepted terms at least once.
  static Future<bool> hasAcceptedTerms() async {
    final prefs = await SharedPreferences.getInstance();
    final accepted = prefs.getBool(_termsAcceptedKey) ?? false;

    if (!accepted) return false;

    // Keep version tracking up to date without re-gating app usage.
    final acceptedVersion = prefs.getString(_termsAcceptedVersionKey);
    if (acceptedVersion != currentTermsVersion) {
      await prefs.setString(_termsAcceptedVersionKey, currentTermsVersion);
    }

    return true;
  }

  /// Record that user has accepted the terms
  static Future<void> acceptTerms() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_termsAcceptedKey, true);
    await prefs.setString(_termsAcceptedVersionKey, currentTermsVersion);
    await prefs.setString(
      _termsAcceptedDateKey,
      DateTime.now().toIso8601String(),
    );
  }

  /// Get the date when terms were accepted
  static Future<DateTime?> getAcceptedDate() async {
    final prefs = await SharedPreferences.getInstance();
    final dateStr = prefs.getString(_termsAcceptedDateKey);
    if (dateStr == null) return null;
    return DateTime.tryParse(dateStr);
  }

  /// Reset terms acceptance (for testing or if terms need re-acceptance)
  static Future<void> resetAcceptance() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_termsAcceptedKey);
    await prefs.remove(_termsAcceptedVersionKey);
    await prefs.remove(_termsAcceptedDateKey);
  }

  /// Get the terms and conditions text
  static String getTermsText() {
    return '''
KIVIXA TERMS AND CONDITIONS

Last Updated: May 2026

1. AGREEMENT TO TERMS
These Terms of Service constitute a legally binding agreement made between you and the Kivixa Project ("we," "us," or "our"), concerning your access to and use of the Kivixa application and any related services. By accessing the App, you acknowledge that you have read, understood, and agreed to be bound by all of these Terms.

2. INTELLECTUAL PROPERTY RIGHTS
Our Content: Unless otherwise indicated, the App, including source code, databases, functionality, software, and graphic designs, are owned or controlled by us and are protected by copyright and trademark laws. Access is provided under applicable open-source licenses.

User Content: You retain full ownership of any data you create ("User Content"). Because Kivixa is local-first, we have no access to, nor control over, your User Content.

3. LOCAL-FIRST ARCHITECTURE & DATA RESPONSIBILITY
Zero-Knowledge: You acknowledge that Kivixa operates on a "Zero-Knowledge" model. All data is stored locally on your device.

Backup Responsibility: We do not provide cloud backup services. You are solely responsible for maintaining backups of your data. We are not liable for any data loss resulting from hardware failure, software bugs, app uninstallation, or device loss.

4. LOCAL AI & CONTENT DISCLAIMER
Kivixa provides tools for local AI processing.

Accuracy: AI-generated content may be inaccurate, biased, or "hallucinated." You should not rely on AI-generated output for medical, legal, financial, or high-stakes decision-making.

Liability: The Kivixa Project is not responsible for any content generated by local models or any actions you take based on such content.

5. PROHIBITED ACTIVITIES
You may not use the App to:

Circulate malicious software or scripts.

Engage in any activity that violates local or international laws.

Attempt to bypass or modify the App’s security features.

6. LIMITATION OF LIABILITY & DISCLAIMER
KIVIXA IS PROVIDED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES. WE WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THE APP, INCLUDING BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES.
''';
  }

  /// Get the privacy policy text
  static String getPrivacyPolicyText() {
    return '''
KIVIXA PRIVACY POLICY
Last Updated: May 2026

1. OUR PRIVACY PHILOSOPHY
Privacy is not a "feature" of Kivixa; it is the foundation. Our architecture is designed so that your data is never collected, stored on our servers, or sold to third parties.

2. DATA COLLECTION & PROCESSING
Personal Information: We do not require an account to use Kivixa. We do not collect your name, email address, or phone number.

Usage Data (Telemetry): Kivixa does not include telemetry or "phone home" tracking. We do not know how often you use the app or which features you prefer.

Crash Reporting: Optional crash reports may be generated by your operating system (Android/Windows). These are governed by your OS privacy settings and are not directly collected by Kivixa.

3. LOCAL PROCESSING
On-Device AI: All AI analysis, document summarization, and chat interactions occur strictly on your device's CPU/GPU. No text or data is transmitted to the cloud for processing.

Native Engines: The Rust-based engines process data locally in your device's memory. No data is cached or sent externally.

4. THIRD-PARTY SERVICES
While Kivixa is local-first, you may interact with third-party services through:

GitHub/F-Droid/Winget: If you download updates, these platforms may collect standard technical metadata (IP address, device type) required for file delivery.

External Links: If you click a link within the app, you will be directed to an external site governed by its own privacy policy.

5. DATA SECURITY
Because your data is stored locally, its security depends on the security of your device. We recommend using encrypted storage, biometrics, or strong passwords to protect your device from unauthorized access.

6. CHILDREN'S PRIVACY
Kivixa does not knowingly collect data from anyone. Because all data stays on your device, we have no way to identify the age of our users. We encourage parents to monitor their children's device usage.

7. CONTACT INFORMATION
For any questions regarding these policies, please open an issue on our official GitHub repository.
''';
  }
}
