// This file is generated by the bump_version script.
// Run `dart run scripts/bump_version.dart --help` for more information.

import 'package:kivixa/data/kivixa_version.dart';

/// The current app version as an ordinal number.
const buildNumber = 1003;

/// The current app version as a string.
const buildName = '0.1.3';

/// The year in which the current version was released.
const buildYear = 2025;

/// The current app version as a KivixaVersion object.
final kivixaVersion = KivixaVersion.fromNumber(buildNumber);
