// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kivixa/src/rust/frb_generated.dart';

/// A stored embedding with metadata
class EmbeddingEntry {
  /// Unique identifier (e.g., note path)
  final String id;

  /// The embedding vector
  final Float32List vector;

  /// Optional text preview
  final String? textPreview;

  const EmbeddingEntry({
    required this.id,
    required this.vector,
    this.textPreview,
  });

  @override
  int get hashCode => id.hashCode ^ vector.hashCode ^ textPreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbeddingEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          vector == other.vector &&
          textPreview == other.textPreview;
}

/// Result of a similarity search
class SimilarityResult {
  /// ID of the matched entry
  final String id;

  /// Similarity score (0.0 to 1.0 for cosine similarity)
  final double score;

  /// Optional text preview
  final String? textPreview;

  const SimilarityResult({
    required this.id,
    required this.score,
    this.textPreview,
  });

  @override
  int get hashCode => id.hashCode ^ score.hashCode ^ textPreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimilarityResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          score == other.score &&
          textPreview == other.textPreview;
}
