// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'clustering.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'embeddings.dart';
import 'frb_generated.dart';
import 'graph.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'streaming.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  ClusterAssignment dco_decode_cluster_assignment(dynamic raw);

  @protected
  ClusterInfo dco_decode_cluster_info(dynamic raw);

  @protected
  ClusteringResult dco_decode_clustering_result(dynamic raw);

  @protected
  EmbeddingCluster dco_decode_embedding_cluster(dynamic raw);

  @protected
  EmbeddingEntry dco_decode_embedding_entry(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  GraphEdge dco_decode_graph_edge(dynamic raw);

  @protected
  GraphNode dco_decode_graph_node(dynamic raw);

  @protected
  GraphState dco_decode_graph_state(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  KnowledgeGraphAnalysis dco_decode_knowledge_graph_analysis(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ClusterAssignment> dco_decode_list_cluster_assignment(dynamic raw);

  @protected
  List<ClusterInfo> dco_decode_list_cluster_info(dynamic raw);

  @protected
  List<EmbeddingCluster> dco_decode_list_embedding_cluster(dynamic raw);

  @protected
  List<EmbeddingEntry> dco_decode_list_embedding_entry(dynamic raw);

  @protected
  List<GraphEdge> dco_decode_list_graph_edge(dynamic raw);

  @protected
  List<GraphNode> dco_decode_list_graph_node(dynamic raw);

  @protected
  List<NodePosition> dco_decode_list_node_position(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SemanticEdge> dco_decode_list_semantic_edge(dynamic raw);

  @protected
  List<SimilarityResult> dco_decode_list_similarity_result(dynamic raw);

  @protected
  NodePosition dco_decode_node_position(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  Float32List? dco_decode_opt_list_prim_f_32_strict(dynamic raw);

  @protected
  List<(String, String)>? dco_decode_opt_list_record_string_string(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SemanticEdge dco_decode_semantic_edge(dynamic raw);

  @protected
  SemanticEdgeResult dco_decode_semantic_edge_result(dynamic raw);

  @protected
  SimilarityResult dco_decode_similarity_result(dynamic raw);

  @protected
  StreamGraphStats dco_decode_stream_graph_stats(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  ClusterAssignment sse_decode_cluster_assignment(SseDeserializer deserializer);

  @protected
  ClusterInfo sse_decode_cluster_info(SseDeserializer deserializer);

  @protected
  ClusteringResult sse_decode_clustering_result(SseDeserializer deserializer);

  @protected
  EmbeddingCluster sse_decode_embedding_cluster(SseDeserializer deserializer);

  @protected
  EmbeddingEntry sse_decode_embedding_entry(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  GraphEdge sse_decode_graph_edge(SseDeserializer deserializer);

  @protected
  GraphNode sse_decode_graph_node(SseDeserializer deserializer);

  @protected
  GraphState sse_decode_graph_state(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  KnowledgeGraphAnalysis sse_decode_knowledge_graph_analysis(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ClusterAssignment> sse_decode_list_cluster_assignment(
    SseDeserializer deserializer,
  );

  @protected
  List<ClusterInfo> sse_decode_list_cluster_info(SseDeserializer deserializer);

  @protected
  List<EmbeddingCluster> sse_decode_list_embedding_cluster(
    SseDeserializer deserializer,
  );

  @protected
  List<EmbeddingEntry> sse_decode_list_embedding_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<GraphEdge> sse_decode_list_graph_edge(SseDeserializer deserializer);

  @protected
  List<GraphNode> sse_decode_list_graph_node(SseDeserializer deserializer);

  @protected
  List<NodePosition> sse_decode_list_node_position(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SemanticEdge> sse_decode_list_semantic_edge(
    SseDeserializer deserializer,
  );

  @protected
  List<SimilarityResult> sse_decode_list_similarity_result(
    SseDeserializer deserializer,
  );

  @protected
  NodePosition sse_decode_node_position(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  Float32List? sse_decode_opt_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)>? sse_decode_opt_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SemanticEdge sse_decode_semantic_edge(SseDeserializer deserializer);

  @protected
  SemanticEdgeResult sse_decode_semantic_edge_result(
    SseDeserializer deserializer,
  );

  @protected
  SimilarityResult sse_decode_similarity_result(SseDeserializer deserializer);

  @protected
  StreamGraphStats sse_decode_stream_graph_stats(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Float> cst_encode_box_autoadd_f_32(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_f_32(cst_encode_f_32(raw));
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_box_autoadd_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_32(cst_encode_i_32(raw));
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_u_32(cst_encode_u_32(raw));
  }

  @protected
  ffi.Pointer<ffi.UintPtr> cst_encode_box_autoadd_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_usize(cst_encode_usize(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_cluster_assignment>
  cst_encode_list_cluster_assignment(List<ClusterAssignment> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_cluster_assignment(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_cluster_assignment(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_cluster_info> cst_encode_list_cluster_info(
    List<ClusterInfo> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_cluster_info(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_cluster_info(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_embedding_cluster>
  cst_encode_list_embedding_cluster(List<EmbeddingCluster> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_embedding_cluster(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_embedding_cluster(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_embedding_entry> cst_encode_list_embedding_entry(
    List<EmbeddingEntry> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_embedding_entry(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_embedding_entry(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_graph_edge> cst_encode_list_graph_edge(
    List<GraphEdge> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_graph_edge(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_graph_edge(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_graph_node> cst_encode_list_graph_node(
    List<GraphNode> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_graph_node(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_graph_node(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_node_position> cst_encode_list_node_position(
    List<NodePosition> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_node_position(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_node_position(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_f_32_loose> cst_encode_list_prim_f_32_loose(
    List<double> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_f_32_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_f_32_strict> cst_encode_list_prim_f_32_strict(
    Float32List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_f_32_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_record_string_string>
  cst_encode_list_record_string_string(List<(String, String)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_record_string_string(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_record_string_string(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_semantic_edge> cst_encode_list_semantic_edge(
    List<SemanticEdge> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_semantic_edge(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_semantic_edge(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_similarity_result>
  cst_encode_list_similarity_result(List<SimilarityResult> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_similarity_result(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_similarity_result(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Float> cst_encode_opt_box_autoadd_f_32(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_f_32(raw);
  }

  @protected
  ffi.Pointer<ffi.Int32> cst_encode_opt_box_autoadd_i_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_32(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  ffi.Pointer<ffi.UintPtr> cst_encode_opt_box_autoadd_usize(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_usize(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_f_32_strict>
  cst_encode_opt_list_prim_f_32_strict(Float32List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_prim_f_32_strict(raw);
  }

  @protected
  ffi.Pointer<wire_cst_list_record_string_string>
  cst_encode_opt_list_record_string_string(List<(String, String)>? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_list_record_string_string(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_cluster_assignment(
    ClusterAssignment apiObj,
    wire_cst_cluster_assignment wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.cluster_id = cst_encode_usize(apiObj.clusterId);
    wireObj.color = cst_encode_String(apiObj.color);
  }

  @protected
  void cst_api_fill_to_wire_cluster_info(
    ClusterInfo apiObj,
    wire_cst_cluster_info wireObj,
  ) {
    wireObj.id = cst_encode_usize(apiObj.id);
    wireObj.size = cst_encode_usize(apiObj.size);
    wireObj.color = cst_encode_String(apiObj.color);
    wireObj.centroid = cst_encode_opt_list_prim_f_32_strict(apiObj.centroid);
  }

  @protected
  void cst_api_fill_to_wire_clustering_result(
    ClusteringResult apiObj,
    wire_cst_clustering_result wireObj,
  ) {
    wireObj.assignments = cst_encode_list_cluster_assignment(
      apiObj.assignments,
    );
    wireObj.clusters = cst_encode_list_cluster_info(apiObj.clusters);
    wireObj.k = cst_encode_usize(apiObj.k);
  }

  @protected
  void cst_api_fill_to_wire_embedding_cluster(
    EmbeddingCluster apiObj,
    wire_cst_embedding_cluster wireObj,
  ) {
    wireObj.ids = cst_encode_list_String(apiObj.ids);
  }

  @protected
  void cst_api_fill_to_wire_embedding_entry(
    EmbeddingEntry apiObj,
    wire_cst_embedding_entry wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.vector = cst_encode_list_prim_f_32_strict(apiObj.vector);
    wireObj.text_preview = cst_encode_opt_String(apiObj.textPreview);
  }

  @protected
  void cst_api_fill_to_wire_graph_edge(
    GraphEdge apiObj,
    wire_cst_graph_edge wireObj,
  ) {
    wireObj.source = cst_encode_String(apiObj.source);
    wireObj.target = cst_encode_String(apiObj.target);
    wireObj.weight = cst_encode_f_32(apiObj.weight);
    wireObj.edge_type = cst_encode_String(apiObj.edgeType);
  }

  @protected
  void cst_api_fill_to_wire_graph_node(
    GraphNode apiObj,
    wire_cst_graph_node wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.label = cst_encode_String(apiObj.label);
    wireObj.node_type = cst_encode_String(apiObj.nodeType);
    wireObj.x = cst_encode_f_32(apiObj.x);
    wireObj.y = cst_encode_f_32(apiObj.y);
    wireObj.color = cst_encode_opt_String(apiObj.color);
    wireObj.metadata = cst_encode_opt_String(apiObj.metadata);
  }

  @protected
  void cst_api_fill_to_wire_graph_state(
    GraphState apiObj,
    wire_cst_graph_state wireObj,
  ) {
    wireObj.nodes = cst_encode_list_graph_node(apiObj.nodes);
    wireObj.edges = cst_encode_list_graph_edge(apiObj.edges);
  }

  @protected
  void cst_api_fill_to_wire_knowledge_graph_analysis(
    KnowledgeGraphAnalysis apiObj,
    wire_cst_knowledge_graph_analysis wireObj,
  ) {
    cst_api_fill_to_wire_clustering_result(
      apiObj.clustering,
      wireObj.clustering,
    );
    cst_api_fill_to_wire_semantic_edge_result(
      apiObj.semanticEdges,
      wireObj.semantic_edges,
    );
  }

  @protected
  void cst_api_fill_to_wire_node_position(
    NodePosition apiObj,
    wire_cst_node_position wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.x = cst_encode_f_32(apiObj.x);
    wireObj.y = cst_encode_f_32(apiObj.y);
    wireObj.radius = cst_encode_f_32(apiObj.radius);
    wireObj.color = cst_encode_u_32(apiObj.color);
    wireObj.node_type = cst_encode_String(apiObj.nodeType);
  }

  @protected
  void cst_api_fill_to_wire_record_string_string(
    (String, String) apiObj,
    wire_cst_record_string_string wireObj,
  ) {
    wireObj.field0 = cst_encode_String(apiObj.$1);
    wireObj.field1 = cst_encode_String(apiObj.$2);
  }

  @protected
  void cst_api_fill_to_wire_semantic_edge(
    SemanticEdge apiObj,
    wire_cst_semantic_edge wireObj,
  ) {
    wireObj.source = cst_encode_String(apiObj.source);
    wireObj.target = cst_encode_String(apiObj.target);
    wireObj.similarity = cst_encode_f_32(apiObj.similarity);
    wireObj.is_ghost = cst_encode_bool(apiObj.isGhost);
  }

  @protected
  void cst_api_fill_to_wire_semantic_edge_result(
    SemanticEdgeResult apiObj,
    wire_cst_semantic_edge_result wireObj,
  ) {
    wireObj.edges = cst_encode_list_semantic_edge(apiObj.edges);
    wireObj.count = cst_encode_usize(apiObj.count);
  }

  @protected
  void cst_api_fill_to_wire_similarity_result(
    SimilarityResult apiObj,
    wire_cst_similarity_result wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.score = cst_encode_f_32(apiObj.score);
    wireObj.text_preview = cst_encode_opt_String(apiObj.textPreview);
  }

  @protected
  void cst_api_fill_to_wire_stream_graph_stats(
    StreamGraphStats apiObj,
    wire_cst_stream_graph_stats wireObj,
  ) {
    wireObj.node_count = cst_encode_usize(apiObj.nodeCount);
    wireObj.edge_count = cst_encode_usize(apiObj.edgeCount);
    wireObj.visible_count = cst_encode_usize(apiObj.visibleCount);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_cluster_assignment(
    ClusterAssignment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cluster_info(ClusterInfo self, SseSerializer serializer);

  @protected
  void sse_encode_clustering_result(
    ClusteringResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_embedding_cluster(
    EmbeddingCluster self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_embedding_entry(
    EmbeddingEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_graph_edge(GraphEdge self, SseSerializer serializer);

  @protected
  void sse_encode_graph_node(GraphNode self, SseSerializer serializer);

  @protected
  void sse_encode_graph_state(GraphState self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_knowledge_graph_analysis(
    KnowledgeGraphAnalysis self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cluster_assignment(
    List<ClusterAssignment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cluster_info(
    List<ClusterInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_embedding_cluster(
    List<EmbeddingCluster> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_embedding_entry(
    List<EmbeddingEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_graph_edge(
    List<GraphEdge> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_graph_node(
    List<GraphNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_node_position(
    List<NodePosition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_semantic_edge(
    List<SemanticEdge> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_similarity_result(
    List<SimilarityResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_node_position(NodePosition self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_f_32_strict(
    Float32List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_record_string_string(
    List<(String, String)>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_edge(SemanticEdge self, SseSerializer serializer);

  @protected
  void sse_encode_semantic_edge_result(
    SemanticEdgeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_similarity_result(
    SimilarityResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stream_graph_stats(
    StreamGraphStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__add_graph_edge(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> source,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> target,
    double weight,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> edge_type,
  ) {
    return _wire__crate__api__add_graph_edge(
      port_,
      source,
      target,
      weight,
      edge_type,
    );
  }

  late final _wire__crate__api__add_graph_edgePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Float,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__add_graph_edge');
  late final _wire__crate__api__add_graph_edge =
      _wire__crate__api__add_graph_edgePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              double,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__add_graph_edges(
    int port_,
    ffi.Pointer<wire_cst_list_graph_edge> edges,
  ) {
    return _wire__crate__api__add_graph_edges(port_, edges);
  }

  late final _wire__crate__api__add_graph_edgesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_graph_edge>)
        >
      >('frbgen_kivixa_wire__crate__api__add_graph_edges');
  late final _wire__crate__api__add_graph_edges =
      _wire__crate__api__add_graph_edgesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_graph_edge>)
          >();

  void wire__crate__api__add_graph_node(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> label,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> node_type,
    double x,
    double y,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> color,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> metadata,
  ) {
    return _wire__crate__api__add_graph_node(
      port_,
      id,
      label,
      node_type,
      x,
      y,
      color,
      metadata,
    );
  }

  late final _wire__crate__api__add_graph_nodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Float,
            ffi.Float,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__add_graph_node');
  late final _wire__crate__api__add_graph_node =
      _wire__crate__api__add_graph_nodePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              double,
              double,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__add_graph_nodes(
    int port_,
    ffi.Pointer<wire_cst_list_graph_node> nodes,
  ) {
    return _wire__crate__api__add_graph_nodes(port_, nodes);
  }

  late final _wire__crate__api__add_graph_nodesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_graph_node>)
        >
      >('frbgen_kivixa_wire__crate__api__add_graph_nodes');
  late final _wire__crate__api__add_graph_nodes =
      _wire__crate__api__add_graph_nodesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_graph_node>)
          >();

  void wire__crate__api__add_stream_edge(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> from_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> to_id,
    double strength,
  ) {
    return _wire__crate__api__add_stream_edge(port_, from_id, to_id, strength);
  }

  late final _wire__crate__api__add_stream_edgePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Float,
          )
        >
      >('frbgen_kivixa_wire__crate__api__add_stream_edge');
  late final _wire__crate__api__add_stream_edge =
      _wire__crate__api__add_stream_edgePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              double,
            )
          >();

  void wire__crate__api__add_stream_node(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    double x,
    double y,
    double radius,
    int color,
  ) {
    return _wire__crate__api__add_stream_node(port_, id, x, y, radius, color);
  }

  late final _wire__crate__api__add_stream_nodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Float,
            ffi.Float,
            ffi.Float,
            ffi.Uint32,
          )
        >
      >('frbgen_kivixa_wire__crate__api__add_stream_node');
  late final _wire__crate__api__add_stream_node =
      _wire__crate__api__add_stream_nodePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              double,
              double,
              double,
              int,
            )
          >();

  void wire__crate__api__analyze_knowledge_graph(
    int port_,
    ffi.Pointer<wire_cst_list_embedding_entry> entries,
    ffi.Pointer<ffi.UintPtr> k,
    ffi.Pointer<ffi.Float> similarity_threshold,
    ffi.Pointer<wire_cst_list_record_string_string> existing_links,
  ) {
    return _wire__crate__api__analyze_knowledge_graph(
      port_,
      entries,
      k,
      similarity_threshold,
      existing_links,
    );
  }

  late final _wire__crate__api__analyze_knowledge_graphPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_embedding_entry>,
            ffi.Pointer<ffi.UintPtr>,
            ffi.Pointer<ffi.Float>,
            ffi.Pointer<wire_cst_list_record_string_string>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__analyze_knowledge_graph');
  late final _wire__crate__api__analyze_knowledge_graph =
      _wire__crate__api__analyze_knowledge_graphPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_embedding_entry>,
              ffi.Pointer<ffi.UintPtr>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<wire_cst_list_record_string_string>,
            )
          >();

  void wire__crate__api__batch_embed(
    int port_,
    ffi.Pointer<wire_cst_list_String> texts,
  ) {
    return _wire__crate__api__batch_embed(port_, texts);
  }

  late final _wire__crate__api__batch_embedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>)
        >
      >('frbgen_kivixa_wire__crate__api__batch_embed');
  late final _wire__crate__api__batch_embed = _wire__crate__api__batch_embedPtr
      .asFunction<void Function(int, ffi.Pointer<wire_cst_list_String>)>();

  void wire__crate__api__chat_completion(
    int port_,
    ffi.Pointer<wire_cst_list_record_string_string> messages,
    ffi.Pointer<ffi.Uint32> max_tokens,
  ) {
    return _wire__crate__api__chat_completion(port_, messages, max_tokens);
  }

  late final _wire__crate__api__chat_completionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_record_string_string>,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__chat_completion');
  late final _wire__crate__api__chat_completion =
      _wire__crate__api__chat_completionPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_record_string_string>,
              ffi.Pointer<ffi.Uint32>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__clear_graph() {
    return _wire__crate__api__clear_graph();
  }

  late final _wire__crate__api__clear_graphPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__clear_graph',
      );
  late final _wire__crate__api__clear_graph = _wire__crate__api__clear_graphPtr
      .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__clear_stream_graph() {
    return _wire__crate__api__clear_stream_graph();
  }

  late final _wire__crate__api__clear_stream_graphPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__clear_stream_graph',
      );
  late final _wire__crate__api__clear_stream_graph =
      _wire__crate__api__clear_stream_graphPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__cluster_embeddings(
    int port_,
    ffi.Pointer<wire_cst_list_embedding_entry> entries,
    double threshold,
  ) {
    return _wire__crate__api__cluster_embeddings(port_, entries, threshold);
  }

  late final _wire__crate__api__cluster_embeddingsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_embedding_entry>,
            ffi.Float,
          )
        >
      >('frbgen_kivixa_wire__crate__api__cluster_embeddings');
  late final _wire__crate__api__cluster_embeddings =
      _wire__crate__api__cluster_embeddingsPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_embedding_entry>,
              double,
            )
          >();

  void wire__crate__api__cluster_notes(
    int port_,
    ffi.Pointer<wire_cst_list_embedding_entry> entries,
    ffi.Pointer<ffi.UintPtr> k,
    ffi.Pointer<ffi.UintPtr> max_iterations,
  ) {
    return _wire__crate__api__cluster_notes(port_, entries, k, max_iterations);
  }

  late final _wire__crate__api__cluster_notesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_embedding_entry>,
            ffi.Pointer<ffi.UintPtr>,
            ffi.Pointer<ffi.UintPtr>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__cluster_notes');
  late final _wire__crate__api__cluster_notes =
      _wire__crate__api__cluster_notesPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_embedding_entry>,
              ffi.Pointer<ffi.UintPtr>,
              ffi.Pointer<ffi.UintPtr>,
            )
          >();

  void wire__crate__api__compute_graph_layout(
    int port_,
    ffi.Pointer<ffi.Uint32> iterations,
  ) {
    return _wire__crate__api__compute_graph_layout(port_, iterations);
  }

  late final _wire__crate__api__compute_graph_layoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Uint32>)
        >
      >('frbgen_kivixa_wire__crate__api__compute_graph_layout');
  late final _wire__crate__api__compute_graph_layout =
      _wire__crate__api__compute_graph_layoutPtr
          .asFunction<void Function(int, ffi.Pointer<ffi.Uint32>)>();

  void wire__crate__api__connect_note_to_topics(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> note_id,
    ffi.Pointer<wire_cst_list_String> topic_ids,
  ) {
    return _wire__crate__api__connect_note_to_topics(port_, note_id, topic_ids);
  }

  late final _wire__crate__api__connect_note_to_topicsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__connect_note_to_topics');
  late final _wire__crate__api__connect_note_to_topics =
      _wire__crate__api__connect_note_to_topicsPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_String>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__cosine_similarity(
    ffi.Pointer<wire_cst_list_prim_f_32_loose> a,
    ffi.Pointer<wire_cst_list_prim_f_32_loose> b,
  ) {
    return _wire__crate__api__cosine_similarity(a, b);
  }

  late final _wire__crate__api__cosine_similarityPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_f_32_loose>,
            ffi.Pointer<wire_cst_list_prim_f_32_loose>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__cosine_similarity');
  late final _wire__crate__api__cosine_similarity =
      _wire__crate__api__cosine_similarityPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_f_32_loose>,
              ffi.Pointer<wire_cst_list_prim_f_32_loose>,
            )
          >();

  void wire__crate__api__discover_semantic_edges(
    int port_,
    ffi.Pointer<wire_cst_list_embedding_entry> entries,
    ffi.Pointer<ffi.Float> threshold,
    ffi.Pointer<wire_cst_list_record_string_string> existing_links,
  ) {
    return _wire__crate__api__discover_semantic_edges(
      port_,
      entries,
      threshold,
      existing_links,
    );
  }

  late final _wire__crate__api__discover_semantic_edgesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_embedding_entry>,
            ffi.Pointer<ffi.Float>,
            ffi.Pointer<wire_cst_list_record_string_string>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__discover_semantic_edges');
  late final _wire__crate__api__discover_semantic_edges =
      _wire__crate__api__discover_semantic_edgesPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_embedding_entry>,
              ffi.Pointer<ffi.Float>,
              ffi.Pointer<wire_cst_list_record_string_string>,
            )
          >();

  void wire__crate__api__extract_topics(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
    ffi.Pointer<ffi.Uint32> num_topics,
  ) {
    return _wire__crate__api__extract_topics(port_, text, num_topics);
  }

  late final _wire__crate__api__extract_topicsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__extract_topics');
  late final _wire__crate__api__extract_topics =
      _wire__crate__api__extract_topicsPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.Uint32>,
            )
          >();

  void wire__crate__api__find_similar(
    int port_,
    ffi.Pointer<wire_cst_list_prim_f_32_loose> query,
    ffi.Pointer<wire_cst_list_embedding_entry> entries,
    int top_k,
    double threshold,
  ) {
    return _wire__crate__api__find_similar(
      port_,
      query,
      entries,
      top_k,
      threshold,
    );
  }

  late final _wire__crate__api__find_similarPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_f_32_loose>,
            ffi.Pointer<wire_cst_list_embedding_entry>,
            ffi.UintPtr,
            ffi.Float,
          )
        >
      >('frbgen_kivixa_wire__crate__api__find_similar');
  late final _wire__crate__api__find_similar =
      _wire__crate__api__find_similarPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_f_32_loose>,
              ffi.Pointer<wire_cst_list_embedding_entry>,
              int,
              double,
            )
          >();

  void wire__crate__api__generate_text(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> prompt,
    ffi.Pointer<ffi.Uint32> max_tokens,
  ) {
    return _wire__crate__api__generate_text(port_, prompt, max_tokens);
  }

  late final _wire__crate__api__generate_textPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__generate_text');
  late final _wire__crate__api__generate_text =
      _wire__crate__api__generate_textPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.Uint32>,
            )
          >();

  void wire__crate__api__get_embedding(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
  ) {
    return _wire__crate__api__get_embedding(port_, text);
  }

  late final _wire__crate__api__get_embeddingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__get_embedding');
  late final _wire__crate__api__get_embedding =
      _wire__crate__api__get_embeddingPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  WireSyncRust2DartDco wire__crate__api__get_embedding_dimension() {
    return _wire__crate__api__get_embedding_dimension();
  }

  late final _wire__crate__api__get_embedding_dimensionPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__get_embedding_dimension',
      );
  late final _wire__crate__api__get_embedding_dimension =
      _wire__crate__api__get_embedding_dimensionPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__get_graph_state(int port_) {
    return _wire__crate__api__get_graph_state(port_);
  }

  late final _wire__crate__api__get_graph_statePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_kivixa_wire__crate__api__get_graph_state',
      );
  late final _wire__crate__api__get_graph_state =
      _wire__crate__api__get_graph_statePtr.asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__get_model_type() {
    return _wire__crate__api__get_model_type();
  }

  late final _wire__crate__api__get_model_typePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__get_model_type',
      );
  late final _wire__crate__api__get_model_type =
      _wire__crate__api__get_model_typePtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__get_or_create_topic_hub(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> topic,
  ) {
    return _wire__crate__api__get_or_create_topic_hub(port_, topic);
  }

  late final _wire__crate__api__get_or_create_topic_hubPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__get_or_create_topic_hub');
  late final _wire__crate__api__get_or_create_topic_hub =
      _wire__crate__api__get_or_create_topic_hubPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  WireSyncRust2DartDco wire__crate__api__get_stream_graph_stats() {
    return _wire__crate__api__get_stream_graph_stats();
  }

  late final _wire__crate__api__get_stream_graph_statsPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__get_stream_graph_stats',
      );
  late final _wire__crate__api__get_stream_graph_stats =
      _wire__crate__api__get_stream_graph_statsPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__get_version() {
    return _wire__crate__api__get_version();
  }

  late final _wire__crate__api__get_versionPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__get_version',
      );
  late final _wire__crate__api__get_version = _wire__crate__api__get_versionPtr
      .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__get_visible_graph_nodes(int port_) {
    return _wire__crate__api__get_visible_graph_nodes(port_);
  }

  late final _wire__crate__api__get_visible_graph_nodesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_kivixa_wire__crate__api__get_visible_graph_nodes',
      );
  late final _wire__crate__api__get_visible_graph_nodes =
      _wire__crate__api__get_visible_graph_nodesPtr
          .asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__health_check() {
    return _wire__crate__api__health_check();
  }

  late final _wire__crate__api__health_checkPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__health_check',
      );
  late final _wire__crate__api__health_check =
      _wire__crate__api__health_checkPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__init_graph() {
    return _wire__crate__api__init_graph();
  }

  late final _wire__crate__api__init_graphPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__init_graph',
      );
  late final _wire__crate__api__init_graph = _wire__crate__api__init_graphPtr
      .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__init_model(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> model_path,
  ) {
    return _wire__crate__api__init_model(model_path);
  }

  late final _wire__crate__api__init_modelPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__init_model');
  late final _wire__crate__api__init_model = _wire__crate__api__init_modelPtr
      .asFunction<
        WireSyncRust2DartDco Function(
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  void wire__crate__api__init_model_with_config(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> model_path,
    int n_gpu_layers,
    int n_ctx,
    int n_threads,
    double temperature,
    double top_p,
    int max_tokens,
    ffi.Pointer<ffi.Int32> model_type,
  ) {
    return _wire__crate__api__init_model_with_config(
      port_,
      model_path,
      n_gpu_layers,
      n_ctx,
      n_threads,
      temperature,
      top_p,
      max_tokens,
      model_type,
    );
  }

  late final _wire__crate__api__init_model_with_configPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Int32,
            ffi.Float,
            ffi.Float,
            ffi.Uint32,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__init_model_with_config');
  late final _wire__crate__api__init_model_with_config =
      _wire__crate__api__init_model_with_configPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
              int,
              double,
              double,
              int,
              ffi.Pointer<ffi.Int32>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__is_graph_stream_running() {
    return _wire__crate__api__is_graph_stream_running();
  }

  late final _wire__crate__api__is_graph_stream_runningPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__is_graph_stream_running',
      );
  late final _wire__crate__api__is_graph_stream_running =
      _wire__crate__api__is_graph_stream_runningPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__is_model_loaded() {
    return _wire__crate__api__is_model_loaded();
  }

  late final _wire__crate__api__is_model_loadedPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__is_model_loaded',
      );
  late final _wire__crate__api__is_model_loaded =
      _wire__crate__api__is_model_loadedPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__pin_stream_node(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    bool pinned,
  ) {
    return _wire__crate__api__pin_stream_node(port_, id, pinned);
  }

  late final _wire__crate__api__pin_stream_nodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Bool,
          )
        >
      >('frbgen_kivixa_wire__crate__api__pin_stream_node');
  late final _wire__crate__api__pin_stream_node =
      _wire__crate__api__pin_stream_nodePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, bool)
          >();

  void wire__crate__api__remove_graph_node(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> node_id,
  ) {
    return _wire__crate__api__remove_graph_node(port_, node_id);
  }

  late final _wire__crate__api__remove_graph_nodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__remove_graph_node');
  late final _wire__crate__api__remove_graph_node =
      _wire__crate__api__remove_graph_nodePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__remove_stream_edge(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> from_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> to_id,
  ) {
    return _wire__crate__api__remove_stream_edge(port_, from_id, to_id);
  }

  late final _wire__crate__api__remove_stream_edgePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__remove_stream_edge');
  late final _wire__crate__api__remove_stream_edge =
      _wire__crate__api__remove_stream_edgePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__remove_stream_node(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__remove_stream_node(port_, id);
  }

  late final _wire__crate__api__remove_stream_nodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__remove_stream_node');
  late final _wire__crate__api__remove_stream_node =
      _wire__crate__api__remove_stream_nodePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__semantic_search(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> query_text,
    ffi.Pointer<wire_cst_list_embedding_entry> entries,
    int top_k,
  ) {
    return _wire__crate__api__semantic_search(
      port_,
      query_text,
      entries,
      top_k,
    );
  }

  late final _wire__crate__api__semantic_searchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_embedding_entry>,
            ffi.UintPtr,
          )
        >
      >('frbgen_kivixa_wire__crate__api__semantic_search');
  late final _wire__crate__api__semantic_search =
      _wire__crate__api__semantic_searchPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_embedding_entry>,
              int,
            )
          >();

  void wire__crate__api__set_stream_node_position(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    double x,
    double y,
  ) {
    return _wire__crate__api__set_stream_node_position(port_, id, x, y);
  }

  late final _wire__crate__api__set_stream_node_positionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Float,
            ffi.Float,
          )
        >
      >('frbgen_kivixa_wire__crate__api__set_stream_node_position');
  late final _wire__crate__api__set_stream_node_position =
      _wire__crate__api__set_stream_node_positionPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              double,
              double,
            )
          >();

  void wire__crate__api__start_graph_stream(int port_) {
    return _wire__crate__api__start_graph_stream(port_);
  }

  late final _wire__crate__api__start_graph_streamPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_kivixa_wire__crate__api__start_graph_stream',
      );
  late final _wire__crate__api__start_graph_stream =
      _wire__crate__api__start_graph_streamPtr.asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__stop_graph_stream() {
    return _wire__crate__api__stop_graph_stream();
  }

  late final _wire__crate__api__stop_graph_streamPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__stop_graph_stream',
      );
  late final _wire__crate__api__stop_graph_stream =
      _wire__crate__api__stop_graph_streamPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__unload_model() {
    return _wire__crate__api__unload_model();
  }

  late final _wire__crate__api__unload_modelPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__unload_model',
      );
  late final _wire__crate__api__unload_model =
      _wire__crate__api__unload_modelPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__update_graph_viewport(
    int port_,
    double x,
    double y,
    double width,
    double height,
    double scale,
  ) {
    return _wire__crate__api__update_graph_viewport(
      port_,
      x,
      y,
      width,
      height,
      scale,
    );
  }

  late final _wire__crate__api__update_graph_viewportPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Float,
            ffi.Float,
            ffi.Float,
            ffi.Float,
            ffi.Float,
          )
        >
      >('frbgen_kivixa_wire__crate__api__update_graph_viewport');
  late final _wire__crate__api__update_graph_viewport =
      _wire__crate__api__update_graph_viewportPtr
          .asFunction<
            void Function(int, double, double, double, double, double)
          >();

  ffi.Pointer<ffi.Float> cst_new_box_autoadd_f_32(double value) {
    return _cst_new_box_autoadd_f_32(value);
  }

  late final _cst_new_box_autoadd_f_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Float> Function(ffi.Float)>>(
        'frbgen_kivixa_cst_new_box_autoadd_f_32',
      );
  late final _cst_new_box_autoadd_f_32 = _cst_new_box_autoadd_f_32Ptr
      .asFunction<ffi.Pointer<ffi.Float> Function(double)>();

  ffi.Pointer<ffi.Int32> cst_new_box_autoadd_i_32(int value) {
    return _cst_new_box_autoadd_i_32(value);
  }

  late final _cst_new_box_autoadd_i_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>(
        'frbgen_kivixa_cst_new_box_autoadd_i_32',
      );
  late final _cst_new_box_autoadd_i_32 = _cst_new_box_autoadd_i_32Ptr
      .asFunction<ffi.Pointer<ffi.Int32> Function(int)>();

  ffi.Pointer<ffi.Uint32> cst_new_box_autoadd_u_32(int value) {
    return _cst_new_box_autoadd_u_32(value);
  }

  late final _cst_new_box_autoadd_u_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint32> Function(ffi.Uint32)>>(
        'frbgen_kivixa_cst_new_box_autoadd_u_32',
      );
  late final _cst_new_box_autoadd_u_32 = _cst_new_box_autoadd_u_32Ptr
      .asFunction<ffi.Pointer<ffi.Uint32> Function(int)>();

  ffi.Pointer<ffi.UintPtr> cst_new_box_autoadd_usize(int value) {
    return _cst_new_box_autoadd_usize(value);
  }

  late final _cst_new_box_autoadd_usizePtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.UintPtr> Function(ffi.UintPtr)>
      >('frbgen_kivixa_cst_new_box_autoadd_usize');
  late final _cst_new_box_autoadd_usize = _cst_new_box_autoadd_usizePtr
      .asFunction<ffi.Pointer<ffi.UintPtr> Function(int)>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_cluster_assignment> cst_new_list_cluster_assignment(
    int len,
  ) {
    return _cst_new_list_cluster_assignment(len);
  }

  late final _cst_new_list_cluster_assignmentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_cluster_assignment> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_cluster_assignment');
  late final _cst_new_list_cluster_assignment =
      _cst_new_list_cluster_assignmentPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_cluster_assignment> Function(int)
          >();

  ffi.Pointer<wire_cst_list_cluster_info> cst_new_list_cluster_info(int len) {
    return _cst_new_list_cluster_info(len);
  }

  late final _cst_new_list_cluster_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_cluster_info> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_cluster_info');
  late final _cst_new_list_cluster_info = _cst_new_list_cluster_infoPtr
      .asFunction<ffi.Pointer<wire_cst_list_cluster_info> Function(int)>();

  ffi.Pointer<wire_cst_list_embedding_cluster> cst_new_list_embedding_cluster(
    int len,
  ) {
    return _cst_new_list_embedding_cluster(len);
  }

  late final _cst_new_list_embedding_clusterPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_embedding_cluster> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_embedding_cluster');
  late final _cst_new_list_embedding_cluster =
      _cst_new_list_embedding_clusterPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_embedding_cluster> Function(int)
          >();

  ffi.Pointer<wire_cst_list_embedding_entry> cst_new_list_embedding_entry(
    int len,
  ) {
    return _cst_new_list_embedding_entry(len);
  }

  late final _cst_new_list_embedding_entryPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_embedding_entry> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_embedding_entry');
  late final _cst_new_list_embedding_entry = _cst_new_list_embedding_entryPtr
      .asFunction<ffi.Pointer<wire_cst_list_embedding_entry> Function(int)>();

  ffi.Pointer<wire_cst_list_graph_edge> cst_new_list_graph_edge(int len) {
    return _cst_new_list_graph_edge(len);
  }

  late final _cst_new_list_graph_edgePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_graph_edge> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_graph_edge');
  late final _cst_new_list_graph_edge = _cst_new_list_graph_edgePtr
      .asFunction<ffi.Pointer<wire_cst_list_graph_edge> Function(int)>();

  ffi.Pointer<wire_cst_list_graph_node> cst_new_list_graph_node(int len) {
    return _cst_new_list_graph_node(len);
  }

  late final _cst_new_list_graph_nodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_graph_node> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_graph_node');
  late final _cst_new_list_graph_node = _cst_new_list_graph_nodePtr
      .asFunction<ffi.Pointer<wire_cst_list_graph_node> Function(int)>();

  ffi.Pointer<wire_cst_list_node_position> cst_new_list_node_position(int len) {
    return _cst_new_list_node_position(len);
  }

  late final _cst_new_list_node_positionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_node_position> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_node_position');
  late final _cst_new_list_node_position = _cst_new_list_node_positionPtr
      .asFunction<ffi.Pointer<wire_cst_list_node_position> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_f_32_loose> cst_new_list_prim_f_32_loose(
    int len,
  ) {
    return _cst_new_list_prim_f_32_loose(len);
  }

  late final _cst_new_list_prim_f_32_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_f_32_loose> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_prim_f_32_loose');
  late final _cst_new_list_prim_f_32_loose = _cst_new_list_prim_f_32_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_f_32_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_f_32_strict> cst_new_list_prim_f_32_strict(
    int len,
  ) {
    return _cst_new_list_prim_f_32_strict(len);
  }

  late final _cst_new_list_prim_f_32_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_f_32_strict> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_prim_f_32_strict');
  late final _cst_new_list_prim_f_32_strict = _cst_new_list_prim_f_32_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_f_32_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_record_string_string>
  cst_new_list_record_string_string(int len) {
    return _cst_new_list_record_string_string(len);
  }

  late final _cst_new_list_record_string_stringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_record_string_string> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_record_string_string');
  late final _cst_new_list_record_string_string =
      _cst_new_list_record_string_stringPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_record_string_string> Function(int)
          >();

  ffi.Pointer<wire_cst_list_semantic_edge> cst_new_list_semantic_edge(int len) {
    return _cst_new_list_semantic_edge(len);
  }

  late final _cst_new_list_semantic_edgePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_semantic_edge> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_semantic_edge');
  late final _cst_new_list_semantic_edge = _cst_new_list_semantic_edgePtr
      .asFunction<ffi.Pointer<wire_cst_list_semantic_edge> Function(int)>();

  ffi.Pointer<wire_cst_list_similarity_result> cst_new_list_similarity_result(
    int len,
  ) {
    return _cst_new_list_similarity_result(len);
  }

  late final _cst_new_list_similarity_resultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_similarity_result> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_similarity_result');
  late final _cst_new_list_similarity_result =
      _cst_new_list_similarity_resultPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_similarity_result> Function(int)
          >();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_graph_edge extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> source;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> target;

  @ffi.Float()
  external double weight;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> edge_type;
}

final class wire_cst_list_graph_edge extends ffi.Struct {
  external ffi.Pointer<wire_cst_graph_edge> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_graph_node extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> label;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> node_type;

  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> color;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> metadata;
}

final class wire_cst_list_graph_node extends ffi.Struct {
  external ffi.Pointer<wire_cst_graph_node> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_f_32_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Float> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_embedding_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_f_32_strict> vector;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text_preview;
}

final class wire_cst_list_embedding_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_embedding_entry> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_record_string_string extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field1;
}

final class wire_cst_list_record_string_string extends ffi.Struct {
  external ffi.Pointer<wire_cst_record_string_string> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_f_32_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Float> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_cluster_assignment extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  @ffi.UintPtr()
  external int cluster_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> color;
}

final class wire_cst_list_cluster_assignment extends ffi.Struct {
  external ffi.Pointer<wire_cst_cluster_assignment> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_cluster_info extends ffi.Struct {
  @ffi.UintPtr()
  external int id;

  @ffi.UintPtr()
  external int size;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> color;

  external ffi.Pointer<wire_cst_list_prim_f_32_strict> centroid;
}

final class wire_cst_list_cluster_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_cluster_info> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_embedding_cluster extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_String> ids;
}

final class wire_cst_list_embedding_cluster extends ffi.Struct {
  external ffi.Pointer<wire_cst_embedding_cluster> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_node_position extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  @ffi.Float()
  external double radius;

  @ffi.Uint32()
  external int color;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> node_type;
}

final class wire_cst_list_node_position extends ffi.Struct {
  external ffi.Pointer<wire_cst_node_position> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_semantic_edge extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> source;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> target;

  @ffi.Float()
  external double similarity;

  @ffi.Bool()
  external bool is_ghost;
}

final class wire_cst_list_semantic_edge extends ffi.Struct {
  external ffi.Pointer<wire_cst_semantic_edge> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_similarity_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  @ffi.Float()
  external double score;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text_preview;
}

final class wire_cst_list_similarity_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_similarity_result> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_clustering_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_cluster_assignment> assignments;

  external ffi.Pointer<wire_cst_list_cluster_info> clusters;

  @ffi.UintPtr()
  external int k;
}

final class wire_cst_graph_state extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_graph_node> nodes;

  external ffi.Pointer<wire_cst_list_graph_edge> edges;
}

final class wire_cst_semantic_edge_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_semantic_edge> edges;

  @ffi.UintPtr()
  external int count;
}

final class wire_cst_knowledge_graph_analysis extends ffi.Struct {
  external wire_cst_clustering_result clustering;

  external wire_cst_semantic_edge_result semantic_edges;
}

final class wire_cst_stream_graph_stats extends ffi.Struct {
  @ffi.UintPtr()
  external int node_count;

  @ffi.UintPtr()
  external int edge_count;

  @ffi.UintPtr()
  external int visible_count;
}
