// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kivixa/src/rust/frb_generated.dart';

/// An edge in the knowledge graph
class GraphEdge {
  /// Source node ID
  final String source;

  /// Target node ID
  final String target;

  /// Edge weight (affects attraction strength)
  final double weight;

  /// Edge type: "topic", "link", or "similarity"
  final String edgeType;

  const GraphEdge({
    required this.source,
    required this.target,
    required this.weight,
    required this.edgeType,
  });

  @override
  int get hashCode =>
      source.hashCode ^ target.hashCode ^ weight.hashCode ^ edgeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphEdge &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          target == other.target &&
          weight == other.weight &&
          edgeType == other.edgeType;
}

/// A node in the knowledge graph
class GraphNode {
  /// Unique identifier
  final String id;

  /// Display label
  final String label;

  /// Node type: "note", "topic", or "hub"
  final String nodeType;

  /// X position (computed by physics simulation)
  final double x;

  /// Y position (computed by physics simulation)
  final double y;

  /// Optional color (hex string)
  final String? color;

  /// Additional metadata (JSON string)
  final String? metadata;

  const GraphNode({
    required this.id,
    required this.label,
    required this.nodeType,
    required this.x,
    required this.y,
    this.color,
    this.metadata,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      nodeType.hashCode ^
      x.hashCode ^
      y.hashCode ^
      color.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          nodeType == other.nodeType &&
          x == other.x &&
          y == other.y &&
          color == other.color &&
          metadata == other.metadata;
}

/// The complete graph state
class GraphState {
  final List<GraphNode> nodes;
  final List<GraphEdge> edges;

  const GraphState({required this.nodes, required this.edges});

  @override
  int get hashCode => nodes.hashCode ^ edges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphState &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          edges == other.edges;
}
