// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kivixa/src/rust/frb_generated.dart';

/// Position data sent to Flutter (minimal for performance)
class NodePosition {
  final String id;
  final double x;
  final double y;
  final double radius;
  final int color;
  final String nodeType;

  const NodePosition({
    required this.id,
    required this.x,
    required this.y,
    required this.radius,
    required this.color,
    required this.nodeType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      x.hashCode ^
      y.hashCode ^
      radius.hashCode ^
      color.hashCode ^
      nodeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodePosition &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          x == other.x &&
          y == other.y &&
          radius == other.radius &&
          color == other.color &&
          nodeType == other.nodeType;
}
