// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kivixa/src/rust_math/frb_generated.dart';

/// Result of expression evaluation
class ExpressionResult {
  final bool success;
  final double value;
  final String? error;
  final String formatted;

  const ExpressionResult({
    required this.success,
    required this.value,
    this.error,
    required this.formatted,
  });

  @override
  int get hashCode =>
      success.hashCode ^ value.hashCode ^ error.hashCode ^ formatted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpressionResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          value == other.value &&
          error == other.error &&
          formatted == other.formatted;
}
