// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kivixa/src/rust_math/frb_generated.dart';

class ComplexResult {
  final bool success;
  final double real;
  final double imag;
  final double magnitude;
  final double angleRad;
  final double angleDeg;
  final String formattedRect;
  final String formattedPolar;
  final String? error;

  const ComplexResult({
    required this.success,
    required this.real,
    required this.imag,
    required this.magnitude,
    required this.angleRad,
    required this.angleDeg,
    required this.formattedRect,
    required this.formattedPolar,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      real.hashCode ^
      imag.hashCode ^
      magnitude.hashCode ^
      angleRad.hashCode ^
      angleDeg.hashCode ^
      formattedRect.hashCode ^
      formattedPolar.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComplexResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          real == other.real &&
          imag == other.imag &&
          magnitude == other.magnitude &&
          angleRad == other.angleRad &&
          angleDeg == other.angleDeg &&
          formattedRect == other.formattedRect &&
          formattedPolar == other.formattedPolar &&
          error == other.error;
}
