// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kivixa/src/rust_math/frb_generated.dart';

/// Result of discrete math operations
class DiscreteResult {
  final bool success;
  final BigInt value;
  final String? bigValue;
  final Uint64List values;
  final bool? boolResult;
  final String? error;

  const DiscreteResult({
    required this.success,
    required this.value,
    this.bigValue,
    required this.values,
    this.boolResult,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      value.hashCode ^
      bigValue.hashCode ^
      values.hashCode ^
      boolResult.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscreteResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          value == other.value &&
          bigValue == other.bigValue &&
          values == other.values &&
          boolResult == other.boolResult &&
          error == other.error;
}
