// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:kivixa/src/rust_math/api.dart';
import 'package:kivixa/src/rust_math/basic.dart';
import 'package:kivixa/src/rust_math/calculus.dart';
import 'package:kivixa/src/rust_math/complex.dart';
import 'package:kivixa/src/rust_math/discrete.dart';
import 'package:kivixa/src/rust_math/frb_generated.dart';
import 'package:kivixa/src/rust_math/graphing.dart';
import 'package:kivixa/src/rust_math/matrix.dart';
import 'package:kivixa/src/rust_math/statistics.dart';
import 'package:kivixa/src/rust_math/units.dart';

abstract class MathRustLibApiImplPlatform extends BaseApiImpl<MathRustLibWire> {
  MathRustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  CalculusResult dco_decode_calculus_result(dynamic raw);

  @protected
  ComplexResult dco_decode_complex_result(dynamic raw);

  @protected
  ConfidenceIntervalResult dco_decode_confidence_interval_result(dynamic raw);

  @protected
  CorrelationResult dco_decode_correlation_result(dynamic raw);

  @protected
  DiscreteResult dco_decode_discrete_result(dynamic raw);

  @protected
  DistributionResult dco_decode_distribution_result(dynamic raw);

  @protected
  ExpressionResult dco_decode_expression_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GraphPoint dco_decode_graph_point(dynamic raw);

  @protected
  GraphResult dco_decode_graph_result(dynamic raw);

  @protected
  HypothesisTestResult dco_decode_hypothesis_test_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<GraphPoint> dco_decode_list_graph_point(dynamic raw);

  @protected
  List<Float64List> dco_decode_list_list_prim_f_64_strict(dynamic raw);

  @protected
  List<MatrixResult> dco_decode_list_matrix_result(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(double, double)> dco_decode_list_record_f_64_f_64(dynamic raw);

  @protected
  List<(String, double)> dco_decode_list_record_string_f_64(dynamic raw);

  @protected
  List<UnitResult> dco_decode_list_unit_result(dynamic raw);

  @protected
  MatrixDecomposition dco_decode_matrix_decomposition(dynamic raw);

  @protected
  MatrixResult dco_decode_matrix_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  Float64List? dco_decode_opt_list_prim_f_64_strict(dynamic raw);

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw);

  @protected
  (List<(double, double)>, List<(double, double)>)
  dco_decode_record_list_record_f_64_f_64_list_record_f_64_f_64(dynamic raw);

  @protected
  (String, double) dco_decode_record_string_f_64(dynamic raw);

  @protected
  RegressionResult dco_decode_regression_result(dynamic raw);

  @protected
  SolveResult dco_decode_solve_result(dynamic raw);

  @protected
  StatisticsResult dco_decode_statistics_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnitResult dco_decode_unit_result(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  CalculusResult sse_decode_calculus_result(SseDeserializer deserializer);

  @protected
  ComplexResult sse_decode_complex_result(SseDeserializer deserializer);

  @protected
  ConfidenceIntervalResult sse_decode_confidence_interval_result(
    SseDeserializer deserializer,
  );

  @protected
  CorrelationResult sse_decode_correlation_result(SseDeserializer deserializer);

  @protected
  DiscreteResult sse_decode_discrete_result(SseDeserializer deserializer);

  @protected
  DistributionResult sse_decode_distribution_result(
    SseDeserializer deserializer,
  );

  @protected
  ExpressionResult sse_decode_expression_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GraphPoint sse_decode_graph_point(SseDeserializer deserializer);

  @protected
  GraphResult sse_decode_graph_result(SseDeserializer deserializer);

  @protected
  HypothesisTestResult sse_decode_hypothesis_test_result(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<GraphPoint> sse_decode_list_graph_point(SseDeserializer deserializer);

  @protected
  List<Float64List> sse_decode_list_list_prim_f_64_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<MatrixResult> sse_decode_list_matrix_result(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(double, double)> sse_decode_list_record_f_64_f_64(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, double)> sse_decode_list_record_string_f_64(
    SseDeserializer deserializer,
  );

  @protected
  List<UnitResult> sse_decode_list_unit_result(SseDeserializer deserializer);

  @protected
  MatrixDecomposition sse_decode_matrix_decomposition(
    SseDeserializer deserializer,
  );

  @protected
  MatrixResult sse_decode_matrix_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  Float64List? sse_decode_opt_list_prim_f_64_strict(
    SseDeserializer deserializer,
  );

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer);

  @protected
  (List<(double, double)>, List<(double, double)>)
  sse_decode_record_list_record_f_64_f_64_list_record_f_64_f_64(
    SseDeserializer deserializer,
  );

  @protected
  (String, double) sse_decode_record_string_f_64(SseDeserializer deserializer);

  @protected
  RegressionResult sse_decode_regression_result(SseDeserializer deserializer);

  @protected
  SolveResult sse_decode_solve_result(SseDeserializer deserializer);

  @protected
  StatisticsResult sse_decode_statistics_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnitResult sse_decode_unit_result(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  bool cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_bool(raw);
  }

  @protected
  double cst_encode_box_autoadd_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_f_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_usize(raw);
  }

  @protected
  JSAny cst_encode_calculus_result(CalculusResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_f_64(raw.value),
      cst_encode_opt_String(raw.symbolic),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_complex_result(ComplexResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_f_64(raw.real),
      cst_encode_f_64(raw.imag),
      cst_encode_f_64(raw.magnitude),
      cst_encode_f_64(raw.angleRad),
      cst_encode_f_64(raw.angleDeg),
      cst_encode_String(raw.formattedRect),
      cst_encode_String(raw.formattedPolar),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_confidence_interval_result(ConfidenceIntervalResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_f_64(raw.lower),
      cst_encode_f_64(raw.upper),
      cst_encode_f_64(raw.center),
      cst_encode_f_64(raw.marginOfError),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_correlation_result(CorrelationResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_f_64(raw.correlation),
      cst_encode_f_64(raw.covariance),
      cst_encode_f_64(raw.pValue),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_discrete_result(DiscreteResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_u_64(raw.value),
      cst_encode_opt_String(raw.bigValue),
      cst_encode_list_prim_u_64_strict(raw.values),
      cst_encode_opt_box_autoadd_bool(raw.boolResult),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_distribution_result(DistributionResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_f_64(raw.pdf),
      cst_encode_f_64(raw.cdf),
      cst_encode_f_64(raw.mean),
      cst_encode_f_64(raw.variance),
      cst_encode_f_64(raw.stdDev),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_expression_result(ExpressionResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_f_64(raw.value),
      cst_encode_opt_String(raw.error),
      cst_encode_String(raw.formatted),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_graph_point(GraphPoint raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_f_64(raw.x),
      cst_encode_f_64(raw.y),
      cst_encode_bool(raw.valid),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_graph_result(GraphResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_list_graph_point(raw.points),
      cst_encode_f_64(raw.xMin),
      cst_encode_f_64(raw.xMax),
      cst_encode_f_64(raw.yMin),
      cst_encode_f_64(raw.yMax),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_hypothesis_test_result(HypothesisTestResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_f_64(raw.testStatistic),
      cst_encode_f_64(raw.pValue),
      cst_encode_f_64(raw.criticalValue),
      cst_encode_bool(raw.rejectNull),
      cst_encode_record_f_64_f_64(raw.confidenceInterval),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_graph_point(List<GraphPoint> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_graph_point).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_list_prim_f_64_strict(List<Float64List> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_list_prim_f_64_strict).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_matrix_result(List<MatrixResult> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_matrix_result).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_f_64_loose(List<double> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_f_64_strict(Float64List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_64_strict(Uint64List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.inner.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_record_f_64_f_64(List<(double, double)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_record_f_64_f_64).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_record_string_f_64(List<(String, double)> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_record_string_f_64).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_unit_result(List<UnitResult> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_unit_result).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_matrix_decomposition(MatrixDecomposition raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_String(raw.decompositionType),
      cst_encode_list_matrix_result(raw.matrices),
      cst_encode_list_String(raw.labels),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_matrix_result(MatrixResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_list_prim_f_64_strict(raw.data),
      cst_encode_usize(raw.rows),
      cst_encode_usize(raw.cols),
      cst_encode_opt_box_autoadd_f_64(raw.scalar),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  bool? cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  double? cst_encode_opt_box_autoadd_f_64(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_f_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_usize(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_usize(raw);
  }

  @protected
  JSAny? cst_encode_opt_list_prim_f_64_strict(Float64List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_list_prim_f_64_strict(raw);
  }

  @protected
  JSAny cst_encode_record_f_64_f_64((double, double) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_f_64(raw.$1), cst_encode_f_64(raw.$2)].jsify()!;
  }

  @protected
  JSAny cst_encode_record_list_record_f_64_f_64_list_record_f_64_f_64(
    (List<(double, double)>, List<(double, double)>) raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_record_f_64_f_64(raw.$1),
      cst_encode_list_record_f_64_f_64(raw.$2),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_record_string_f_64((String, double) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.$1), cst_encode_f_64(raw.$2)].jsify()!;
  }

  @protected
  JSAny cst_encode_regression_result(RegressionResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_list_prim_f_64_strict(raw.coefficients),
      cst_encode_f_64(raw.rSquared),
      cst_encode_list_prim_f_64_strict(raw.residuals),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_solve_result(SolveResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_list_prim_f_64_strict(raw.roots),
      cst_encode_usize(raw.iterations),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_statistics_result(StatisticsResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_list_record_string_f_64(raw.values),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_unit_result(UnitResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.success),
      cst_encode_f_64(raw.value),
      cst_encode_String(raw.fromUnit),
      cst_encode_String(raw.toUnit),
      cst_encode_String(raw.formula),
      cst_encode_opt_String(raw.error),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_calculus_result(
    CalculusResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_complex_result(ComplexResult self, SseSerializer serializer);

  @protected
  void sse_encode_confidence_interval_result(
    ConfidenceIntervalResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_correlation_result(
    CorrelationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discrete_result(
    DiscreteResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_distribution_result(
    DistributionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_expression_result(
    ExpressionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_graph_point(GraphPoint self, SseSerializer serializer);

  @protected
  void sse_encode_graph_result(GraphResult self, SseSerializer serializer);

  @protected
  void sse_encode_hypothesis_test_result(
    HypothesisTestResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_graph_point(
    List<GraphPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_f_64_strict(
    List<Float64List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_matrix_result(
    List<MatrixResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_f_64_f_64(
    List<(double, double)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_f_64(
    List<(String, double)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_unit_result(
    List<UnitResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_matrix_decomposition(
    MatrixDecomposition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_matrix_result(MatrixResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_f_64_strict(
    Float64List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_list_record_f_64_f_64_list_record_f_64_f_64(
    (List<(double, double)>, List<(double, double)>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_f_64(
    (String, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_regression_result(
    RegressionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_solve_result(SolveResult self, SseSerializer serializer);

  @protected
  void sse_encode_statistics_result(
    StatisticsResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unit_result(UnitResult self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class MathRustLibWire implements BaseWire {
  MathRustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__anova(
    NativePortType port_,
    JSAny groups,
    double alpha,
  ) => wasmModule.wire__crate__api__anova(port_, groups, alpha);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__catalan(JSAny n) => wasmModule.wire__crate__api__catalan(n);

  void wire__crate__api__chi_squared_test(
    NativePortType port_,
    JSAny observed,
    JSAny expected,
    double alpha,
  ) => wasmModule.wire__crate__api__chi_squared_test(
    port_,
    observed,
    expected,
    alpha,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__combinations(JSAny n, JSAny r) =>
      wasmModule.wire__crate__api__combinations(n, r);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__complex_convert(double real, double imag, bool to_polar) =>
      wasmModule.wire__crate__api__complex_convert(real, imag, to_polar);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__complex_operation(
    double a_real,
    double a_imag,
    double b_real,
    double b_imag,
    String operation,
  ) => wasmModule.wire__crate__api__complex_operation(
    a_real,
    a_imag,
    b_real,
    b_imag,
    operation,
  );

  void wire__crate__api__compute_limit(
    NativePortType port_,
    String expression,
    String variable,
    double approach_value,
    bool from_left,
    bool from_right,
  ) => wasmModule.wire__crate__api__compute_limit(
    port_,
    expression,
    variable,
    approach_value,
    from_left,
    from_right,
  );

  void wire__crate__api__compute_statistics(NativePortType port_, JSAny data) =>
      wasmModule.wire__crate__api__compute_statistics(port_, data);

  void wire__crate__api__confidence_interval_mean(
    NativePortType port_,
    JSAny data,
    double confidence_level,
  ) => wasmModule.wire__crate__api__confidence_interval_mean(
    port_,
    data,
    confidence_level,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__confidence_interval_proportion(
    JSAny successes,
    JSAny n,
    double confidence_level,
  ) => wasmModule.wire__crate__api__confidence_interval_proportion(
    successes,
    n,
    confidence_level,
  );

  void wire__crate__api__confidence_interval_variance(
    NativePortType port_,
    JSAny data,
    double confidence_level,
  ) => wasmModule.wire__crate__api__confidence_interval_variance(
    port_,
    data,
    confidence_level,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__convert_number_system(
    String value,
    int from_base,
    int to_base,
  ) => wasmModule.wire__crate__api__convert_number_system(
    value,
    from_base,
    to_base,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__convert_to_all_units(double value, String from_unit) =>
      wasmModule.wire__crate__api__convert_to_all_units(value, from_unit);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__convert_unit(
    double value,
    String from_unit,
    String to_unit,
  ) => wasmModule.wire__crate__api__convert_unit(value, from_unit, to_unit);

  void wire__crate__api__correlation_covariance(
    NativePortType port_,
    JSAny x,
    JSAny y,
  ) => wasmModule.wire__crate__api__correlation_covariance(port_, x, y);

  void wire__crate__api__derivative_graph(
    NativePortType port_,
    String expression,
    String variable,
    JSAny x_values,
  ) => wasmModule.wire__crate__api__derivative_graph(
    port_,
    expression,
    variable,
    x_values,
  );

  void wire__crate__api__differentiate(
    NativePortType port_,
    String expression,
    String variable,
    double point,
    int order,
  ) => wasmModule.wire__crate__api__differentiate(
    port_,
    expression,
    variable,
    point,
    order,
  );

  void wire__crate__api__distribution_compute(
    NativePortType port_,
    String distribution_type,
    JSAny params,
    double x,
  ) => wasmModule.wire__crate__api__distribution_compute(
    port_,
    distribution_type,
    params,
    x,
  );

  void wire__crate__api__double_integral(
    NativePortType port_,
    String expression,
    String x_var,
    String y_var,
    double x_min,
    double x_max,
    double y_min,
    double y_max,
    int num_intervals,
  ) => wasmModule.wire__crate__api__double_integral(
    port_,
    expression,
    x_var,
    y_var,
    x_min,
    x_max,
    y_min,
    y_max,
    num_intervals,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__euler_totient(JSAny n) =>
      wasmModule.wire__crate__api__euler_totient(n);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__evaluate_expression(String expression) =>
      wasmModule.wire__crate__api__evaluate_expression(expression);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__evaluate_formula(
    String formula,
    JSAny variables,
    JSAny values,
  ) =>
      wasmModule.wire__crate__api__evaluate_formula(formula, variables, values);

  void wire__crate__api__evaluate_graph_points(
    NativePortType port_,
    String expression,
    String variable,
    JSAny x_values,
  ) => wasmModule.wire__crate__api__evaluate_graph_points(
    port_,
    expression,
    variable,
    x_values,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__factorial(JSAny n) =>
      wasmModule.wire__crate__api__factorial(n);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__fibonacci(JSAny n) =>
      wasmModule.wire__crate__api__fibonacci(n);

  void wire__crate__api__find_extrema(
    NativePortType port_,
    String expression,
    String variable,
    double x_min,
    double x_max,
    JSAny num_samples,
  ) => wasmModule.wire__crate__api__find_extrema(
    port_,
    expression,
    variable,
    x_min,
    x_max,
    num_samples,
  );

  void wire__crate__api__find_graph_roots(
    NativePortType port_,
    String expression,
    String variable,
    double x_min,
    double x_max,
    JSAny num_samples,
  ) => wasmModule.wire__crate__api__find_graph_roots(
    port_,
    expression,
    variable,
    x_min,
    x_max,
    num_samples,
  );

  void wire__crate__api__find_roots_in_interval(
    NativePortType port_,
    String expression,
    String variable,
    double start,
    double end,
    int num_samples,
  ) => wasmModule.wire__crate__api__find_roots_in_interval(
    port_,
    expression,
    variable,
    start,
    end,
    num_samples,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__gcd(JSAny a, JSAny b) =>
      wasmModule.wire__crate__api__gcd(a, b);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_x_range(
    double start,
    double end,
    JSAny num_points,
  ) => wasmModule.wire__crate__api__generate_x_range(start, end, num_points);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_constant(String name) =>
      wasmModule.wire__crate__api__get_constant(name);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_unit_categories() =>
      wasmModule.wire__crate__api__get_unit_categories();

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_units_for_category(String category) =>
      wasmModule.wire__crate__api__get_units_for_category(category);

  void wire__crate__api__gradient(
    NativePortType port_,
    String expression,
    JSAny variables,
    JSAny point,
  ) => wasmModule.wire__crate__api__gradient(
    port_,
    expression,
    variables,
    point,
  );

  void wire__crate__api__init_app(NativePortType port_) =>
      wasmModule.wire__crate__api__init_app(port_);

  void wire__crate__api__integral_graph(
    NativePortType port_,
    String expression,
    String variable,
    JSAny x_values,
    double initial_value,
  ) => wasmModule.wire__crate__api__integral_graph(
    port_,
    expression,
    variable,
    x_values,
    initial_value,
  );

  void wire__crate__api__integrate(
    NativePortType port_,
    String expression,
    String variable,
    double lower,
    double upper,
    int num_intervals,
  ) => wasmModule.wire__crate__api__integrate(
    port_,
    expression,
    variable,
    lower,
    upper,
    num_intervals,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__is_perfect(JSAny n) =>
      wasmModule.wire__crate__api__is_perfect(n);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__is_prime(JSAny n) =>
      wasmModule.wire__crate__api__is_prime(n);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__lcm(JSAny a, JSAny b) =>
      wasmModule.wire__crate__api__lcm(a, b);

  void wire__crate__api__line_integral(
    NativePortType port_,
    String expression,
    String x_param,
    String y_param,
    String t_var,
    double t_min,
    double t_max,
    int num_intervals,
  ) => wasmModule.wire__crate__api__line_integral(
    port_,
    expression,
    x_param,
    y_param,
    t_var,
    t_min,
    t_max,
    num_intervals,
  );

  void wire__crate__api__linear_regression(
    NativePortType port_,
    JSAny x_data,
    JSAny y_data,
  ) => wasmModule.wire__crate__api__linear_regression(port_, x_data, y_data);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__list_divisors(JSAny n) =>
      wasmModule.wire__crate__api__list_divisors(n);

  void wire__crate__api__matrix_decomposition(
    NativePortType port_,
    JSAny data,
    JSAny rows,
    JSAny cols,
    String decomposition_type,
  ) => wasmModule.wire__crate__api__matrix_decomposition(
    port_,
    data,
    rows,
    cols,
    decomposition_type,
  );

  void wire__crate__api__matrix_operation(
    NativePortType port_,
    JSAny a_data,
    JSAny a_rows,
    JSAny a_cols,
    JSAny? b_data,
    JSAny? b_rows,
    JSAny? b_cols,
    String operation,
  ) => wasmModule.wire__crate__api__matrix_operation(
    port_,
    a_data,
    a_rows,
    a_cols,
    b_data,
    b_rows,
    b_cols,
    operation,
  );

  void wire__crate__api__matrix_properties(
    NativePortType port_,
    JSAny data,
    JSAny rows,
    JSAny cols,
  ) => wasmModule.wire__crate__api__matrix_properties(port_, data, rows, cols);

  void wire__crate__api__matrix_rref(
    NativePortType port_,
    JSAny data,
    JSAny rows,
    JSAny cols,
  ) => wasmModule.wire__crate__api__matrix_rref(port_, data, rows, cols);

  void wire__crate__api__mixed_partial_derivative(
    NativePortType port_,
    String expression,
    String var1,
    String var2,
    JSAny point,
  ) => wasmModule.wire__crate__api__mixed_partial_derivative(
    port_,
    expression,
    var1,
    var2,
    point,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_add(JSAny a, JSAny b, JSAny m) =>
      wasmModule.wire__crate__api__mod_add(a, b, m);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_divide(JSAny a, JSAny b, JSAny m) =>
      wasmModule.wire__crate__api__mod_divide(a, b, m);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_inverse(JSAny a, JSAny m) =>
      wasmModule.wire__crate__api__mod_inverse(a, m);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_multiply(JSAny a, JSAny b, JSAny m) =>
      wasmModule.wire__crate__api__mod_multiply(a, b, m);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_pow(JSAny base, JSAny exp, JSAny modulus) =>
      wasmModule.wire__crate__api__mod_pow(base, exp, modulus);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_sub(JSAny a, JSAny b, JSAny m) =>
      wasmModule.wire__crate__api__mod_sub(a, b, m);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__parse_formula(String formula) =>
      wasmModule.wire__crate__api__parse_formula(formula);

  void wire__crate__api__partial_derivative(
    NativePortType port_,
    String expression,
    String variable,
    JSAny point,
    int order,
  ) => wasmModule.wire__crate__api__partial_derivative(
    port_,
    expression,
    variable,
    point,
    order,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__permutations(JSAny n, JSAny r) =>
      wasmModule.wire__crate__api__permutations(n, r);

  void wire__crate__api__polynomial_regression(
    NativePortType port_,
    JSAny x_data,
    JSAny y_data,
    JSAny degree,
  ) => wasmModule.wire__crate__api__polynomial_regression(
    port_,
    x_data,
    y_data,
    degree,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__prime_factors(JSAny n) =>
      wasmModule.wire__crate__api__prime_factors(n);

  void wire__crate__api__sieve_primes(NativePortType port_, JSAny n) =>
      wasmModule.wire__crate__api__sieve_primes(port_, n);

  void wire__crate__api__solve_equation(
    NativePortType port_,
    String expression,
    String variable,
    double initial_guess,
    double tolerance,
    int max_iterations,
  ) => wasmModule.wire__crate__api__solve_equation(
    port_,
    expression,
    variable,
    initial_guess,
    tolerance,
    max_iterations,
  );

  void wire__crate__api__t_test(
    NativePortType port_,
    JSAny data,
    double hypothesized_mean,
    double alpha,
  ) => wasmModule.wire__crate__api__t_test(
    port_,
    data,
    hypothesized_mean,
    alpha,
  );

  void wire__crate__api__taylor_coefficients(
    NativePortType port_,
    String expression,
    String variable,
    double around,
    int num_terms,
  ) => wasmModule.wire__crate__api__taylor_coefficients(
    port_,
    expression,
    variable,
    around,
    num_terms,
  );

  void wire__crate__api__triple_integral(
    NativePortType port_,
    String expression,
    String x_var,
    String y_var,
    String z_var,
    double x_min,
    double x_max,
    double y_min,
    double y_max,
    double z_min,
    double z_max,
    int num_intervals,
  ) => wasmModule.wire__crate__api__triple_integral(
    port_,
    expression,
    x_var,
    y_var,
    z_var,
    x_min,
    x_max,
    y_min,
    y_max,
    z_min,
    z_max,
    num_intervals,
  );

  void wire__crate__api__two_sample_t_test(
    NativePortType port_,
    JSAny data1,
    JSAny data2,
    double alpha,
  ) => wasmModule.wire__crate__api__two_sample_t_test(
    port_,
    data1,
    data2,
    alpha,
  );

  void wire__crate__api__two_sample_z_test(
    NativePortType port_,
    JSAny data1,
    JSAny data2,
    double std1,
    double std2,
    double alpha,
  ) => wasmModule.wire__crate__api__two_sample_z_test(
    port_,
    data1,
    data2,
    std1,
    std2,
    alpha,
  );

  void wire__crate__api__z_test(
    NativePortType port_,
    JSAny data,
    double hypothesized_mean,
    double population_std,
    double alpha,
  ) => wasmModule.wire__crate__api__z_test(
    port_,
    data,
    hypothesized_mean,
    population_std,
    alpha,
  );
}

@JS('wasm_bindgen')
external MathRustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type MathRustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__anova(
    NativePortType port_,
    JSAny groups,
    double alpha,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__catalan(JSAny n);

  external void wire__crate__api__chi_squared_test(
    NativePortType port_,
    JSAny observed,
    JSAny expected,
    double alpha,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__combinations(JSAny n, JSAny r);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__complex_convert(double real, double imag, bool to_polar);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__complex_operation(
    double a_real,
    double a_imag,
    double b_real,
    double b_imag,
    String operation,
  );

  external void wire__crate__api__compute_limit(
    NativePortType port_,
    String expression,
    String variable,
    double approach_value,
    bool from_left,
    bool from_right,
  );

  external void wire__crate__api__compute_statistics(
    NativePortType port_,
    JSAny data,
  );

  external void wire__crate__api__confidence_interval_mean(
    NativePortType port_,
    JSAny data,
    double confidence_level,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__confidence_interval_proportion(
    JSAny successes,
    JSAny n,
    double confidence_level,
  );

  external void wire__crate__api__confidence_interval_variance(
    NativePortType port_,
    JSAny data,
    double confidence_level,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__convert_number_system(
    String value,
    int from_base,
    int to_base,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__convert_to_all_units(double value, String from_unit);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__convert_unit(
    double value,
    String from_unit,
    String to_unit,
  );

  external void wire__crate__api__correlation_covariance(
    NativePortType port_,
    JSAny x,
    JSAny y,
  );

  external void wire__crate__api__derivative_graph(
    NativePortType port_,
    String expression,
    String variable,
    JSAny x_values,
  );

  external void wire__crate__api__differentiate(
    NativePortType port_,
    String expression,
    String variable,
    double point,
    int order,
  );

  external void wire__crate__api__distribution_compute(
    NativePortType port_,
    String distribution_type,
    JSAny params,
    double x,
  );

  external void wire__crate__api__double_integral(
    NativePortType port_,
    String expression,
    String x_var,
    String y_var,
    double x_min,
    double x_max,
    double y_min,
    double y_max,
    int num_intervals,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__euler_totient(JSAny n);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__evaluate_expression(String expression);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__evaluate_formula(
    String formula,
    JSAny variables,
    JSAny values,
  );

  external void wire__crate__api__evaluate_graph_points(
    NativePortType port_,
    String expression,
    String variable,
    JSAny x_values,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__factorial(JSAny n);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__fibonacci(JSAny n);

  external void wire__crate__api__find_extrema(
    NativePortType port_,
    String expression,
    String variable,
    double x_min,
    double x_max,
    JSAny num_samples,
  );

  external void wire__crate__api__find_graph_roots(
    NativePortType port_,
    String expression,
    String variable,
    double x_min,
    double x_max,
    JSAny num_samples,
  );

  external void wire__crate__api__find_roots_in_interval(
    NativePortType port_,
    String expression,
    String variable,
    double start,
    double end,
    int num_samples,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__gcd(JSAny a, JSAny b);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__generate_x_range(
    double start,
    double end,
    JSAny num_points,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_constant(String name);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_unit_categories();

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__get_units_for_category(String category);

  external void wire__crate__api__gradient(
    NativePortType port_,
    String expression,
    JSAny variables,
    JSAny point,
  );

  external void wire__crate__api__init_app(NativePortType port_);

  external void wire__crate__api__integral_graph(
    NativePortType port_,
    String expression,
    String variable,
    JSAny x_values,
    double initial_value,
  );

  external void wire__crate__api__integrate(
    NativePortType port_,
    String expression,
    String variable,
    double lower,
    double upper,
    int num_intervals,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__is_perfect(JSAny n);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__is_prime(JSAny n);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__lcm(JSAny a, JSAny b);

  external void wire__crate__api__line_integral(
    NativePortType port_,
    String expression,
    String x_param,
    String y_param,
    String t_var,
    double t_min,
    double t_max,
    int num_intervals,
  );

  external void wire__crate__api__linear_regression(
    NativePortType port_,
    JSAny x_data,
    JSAny y_data,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__list_divisors(JSAny n);

  external void wire__crate__api__matrix_decomposition(
    NativePortType port_,
    JSAny data,
    JSAny rows,
    JSAny cols,
    String decomposition_type,
  );

  external void wire__crate__api__matrix_operation(
    NativePortType port_,
    JSAny a_data,
    JSAny a_rows,
    JSAny a_cols,
    JSAny? b_data,
    JSAny? b_rows,
    JSAny? b_cols,
    String operation,
  );

  external void wire__crate__api__matrix_properties(
    NativePortType port_,
    JSAny data,
    JSAny rows,
    JSAny cols,
  );

  external void wire__crate__api__matrix_rref(
    NativePortType port_,
    JSAny data,
    JSAny rows,
    JSAny cols,
  );

  external void wire__crate__api__mixed_partial_derivative(
    NativePortType port_,
    String expression,
    String var1,
    String var2,
    JSAny point,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_add(JSAny a, JSAny b, JSAny m);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_divide(JSAny a, JSAny b, JSAny m);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_inverse(JSAny a, JSAny m);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_multiply(JSAny a, JSAny b, JSAny m);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_pow(JSAny base, JSAny exp, JSAny modulus);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__mod_sub(JSAny a, JSAny b, JSAny m);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__parse_formula(String formula);

  external void wire__crate__api__partial_derivative(
    NativePortType port_,
    String expression,
    String variable,
    JSAny point,
    int order,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__permutations(JSAny n, JSAny r);

  external void wire__crate__api__polynomial_regression(
    NativePortType port_,
    JSAny x_data,
    JSAny y_data,
    JSAny degree,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__prime_factors(JSAny n);

  external void wire__crate__api__sieve_primes(NativePortType port_, JSAny n);

  external void wire__crate__api__solve_equation(
    NativePortType port_,
    String expression,
    String variable,
    double initial_guess,
    double tolerance,
    int max_iterations,
  );

  external void wire__crate__api__t_test(
    NativePortType port_,
    JSAny data,
    double hypothesized_mean,
    double alpha,
  );

  external void wire__crate__api__taylor_coefficients(
    NativePortType port_,
    String expression,
    String variable,
    double around,
    int num_terms,
  );

  external void wire__crate__api__triple_integral(
    NativePortType port_,
    String expression,
    String x_var,
    String y_var,
    String z_var,
    double x_min,
    double x_max,
    double y_min,
    double y_max,
    double z_min,
    double z_max,
    int num_intervals,
  );

  external void wire__crate__api__two_sample_t_test(
    NativePortType port_,
    JSAny data1,
    JSAny data2,
    double alpha,
  );

  external void wire__crate__api__two_sample_z_test(
    NativePortType port_,
    JSAny data1,
    JSAny data2,
    double std1,
    double std2,
    double alpha,
  );

  external void wire__crate__api__z_test(
    NativePortType port_,
    JSAny data,
    double hypothesized_mean,
    double population_std,
    double alpha,
  );
}
