// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kivixa/src/rust_math/frb_generated.dart';

/// Point on a graph
class GraphPoint {
  final double x;
  final double y;
  final bool valid;

  const GraphPoint({required this.x, required this.y, required this.valid});

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ valid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphPoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          valid == other.valid;
}

/// Result of graph evaluation
class GraphResult {
  final bool success;
  final List<GraphPoint> points;
  final double xMin;
  final double xMax;
  final double yMin;
  final double yMax;
  final String? error;

  const GraphResult({
    required this.success,
    required this.points,
    required this.xMin,
    required this.xMax,
    required this.yMin,
    required this.yMax,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      points.hashCode ^
      xMin.hashCode ^
      xMax.hashCode ^
      yMin.hashCode ^
      yMax.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          points == other.points &&
          xMin == other.xMin &&
          xMax == other.xMax &&
          yMin == other.yMin &&
          yMax == other.yMax &&
          error == other.error;
}
