// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kivixa/src/rust_math/frb_generated.dart';

/// Result of matrix decompositions
class MatrixDecomposition {
  final bool success;
  final String decompositionType;
  final List<MatrixResult> matrices;
  final List<String> labels;
  final String? error;

  const MatrixDecomposition({
    required this.success,
    required this.decompositionType,
    required this.matrices,
    required this.labels,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      decompositionType.hashCode ^
      matrices.hashCode ^
      labels.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatrixDecomposition &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          decompositionType == other.decompositionType &&
          matrices == other.matrices &&
          labels == other.labels &&
          error == other.error;
}

/// Result of matrix operations
class MatrixResult {
  final bool success;
  final Float64List data;
  final BigInt rows;
  final BigInt cols;
  final double? scalar;
  final String? error;

  const MatrixResult({
    required this.success,
    required this.data,
    required this.rows,
    required this.cols,
    this.scalar,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      data.hashCode ^
      rows.hashCode ^
      cols.hashCode ^
      scalar.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatrixResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          data == other.data &&
          rows == other.rows &&
          cols == other.cols &&
          scalar == other.scalar &&
          error == other.error;
}
