// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:kivixa/src/rust_math/frb_generated.dart';

/// Confidence interval result
class ConfidenceIntervalResult {
  final bool success;
  final double lower;
  final double upper;
  final double center;
  final double marginOfError;
  final String? error;

  const ConfidenceIntervalResult({
    required this.success,
    required this.lower,
    required this.upper,
    required this.center,
    required this.marginOfError,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      lower.hashCode ^
      upper.hashCode ^
      center.hashCode ^
      marginOfError.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfidenceIntervalResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          lower == other.lower &&
          upper == other.upper &&
          center == other.center &&
          marginOfError == other.marginOfError &&
          error == other.error;
}

/// Correlation and covariance result
class CorrelationResult {
  final bool success;
  final double correlation;
  final double covariance;
  final double pValue;
  final String? error;

  const CorrelationResult({
    required this.success,
    required this.correlation,
    required this.covariance,
    required this.pValue,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      correlation.hashCode ^
      covariance.hashCode ^
      pValue.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CorrelationResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          correlation == other.correlation &&
          covariance == other.covariance &&
          pValue == other.pValue &&
          error == other.error;
}

/// Result of distribution computations
class DistributionResult {
  final bool success;
  final double pdf;
  final double cdf;
  final double mean;
  final double variance;
  final double stdDev;
  final String? error;

  const DistributionResult({
    required this.success,
    required this.pdf,
    required this.cdf,
    required this.mean,
    required this.variance,
    required this.stdDev,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      pdf.hashCode ^
      cdf.hashCode ^
      mean.hashCode ^
      variance.hashCode ^
      stdDev.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DistributionResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          pdf == other.pdf &&
          cdf == other.cdf &&
          mean == other.mean &&
          variance == other.variance &&
          stdDev == other.stdDev &&
          error == other.error;
}

/// Result of hypothesis tests
class HypothesisTestResult {
  final bool success;
  final double testStatistic;
  final double pValue;
  final double criticalValue;
  final bool rejectNull;
  final (double, double) confidenceInterval;
  final String? error;

  const HypothesisTestResult({
    required this.success,
    required this.testStatistic,
    required this.pValue,
    required this.criticalValue,
    required this.rejectNull,
    required this.confidenceInterval,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      testStatistic.hashCode ^
      pValue.hashCode ^
      criticalValue.hashCode ^
      rejectNull.hashCode ^
      confidenceInterval.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HypothesisTestResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          testStatistic == other.testStatistic &&
          pValue == other.pValue &&
          criticalValue == other.criticalValue &&
          rejectNull == other.rejectNull &&
          confidenceInterval == other.confidenceInterval &&
          error == other.error;
}

/// Result of regression analysis
class RegressionResult {
  final bool success;
  final Float64List coefficients;
  final double rSquared;
  final Float64List residuals;
  final String? error;

  const RegressionResult({
    required this.success,
    required this.coefficients,
    required this.rSquared,
    required this.residuals,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      coefficients.hashCode ^
      rSquared.hashCode ^
      residuals.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegressionResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          coefficients == other.coefficients &&
          rSquared == other.rSquared &&
          residuals == other.residuals &&
          error == other.error;
}

/// Result of statistical computations
class StatisticsResult {
  final bool success;
  final List<(String, double)> values;
  final String? error;

  const StatisticsResult({
    required this.success,
    required this.values,
    this.error,
  });

  @override
  int get hashCode => success.hashCode ^ values.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatisticsResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          values == other.values &&
          error == other.error;
}
