// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/objectbox/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5811485852855989046),
    name: 'NoteEmbedding',
    lastPropertyId: const obx_int.IdUid(7, 1175128141913654342),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1251713209900333799),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4819010201047405998),
        name: 'noteId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 1481202469997831099),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3235069778404937446),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3974208766619727142),
        name: 'preview',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6502032027795711557),
        name: 'vector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 811860160674071369),
        hnswParams: obx_int.ModelHnswParams(dimensions: 3072),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2286421096526390657),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1175128141913654342),
        name: 'metadata',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3967927805202398427),
    name: 'NoteLinkEntity',
    lastPropertyId: const obx_int.IdUid(5, 2012399091908761613),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4747856898682876023),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2269721225067624145),
        name: 'sourceNoteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5040254102698656661),
        name: 'targetNoteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8045327708995203763),
        name: 'linkType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2012399091908761613),
        name: 'similarityScore',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8992994609346571706),
    name: 'NoteTopicLink',
    lastPropertyId: const obx_int.IdUid(4, 3298098903778972371),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7897642486806350076),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1837652577662073457),
        name: 'noteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 31833705717375620),
        name: 'topicId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3298098903778972371),
        name: 'weight',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7252534313616027796),
    name: 'TopicHub',
    lastPropertyId: const obx_int.IdUid(6, 9004901998169032769),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7009369988718897107),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2374036546972152886),
        name: 'topicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 7685607692511380476),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 113690619796656017),
        name: 'label',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7507567786438998186),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 696842363150070093),
        name: 'noteCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9004901998169032769),
        name: 'centroidVector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(4, 2335346740070790527),
        hnswParams: obx_int.ModelHnswParams(dimensions: 3072),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 7252534313616027796),
    lastIndexId: const obx_int.IdUid(4, 2335346740070790527),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    NoteEmbedding: obx_int.EntityDefinition<NoteEmbedding>(
      model: _entities[0],
      toOneRelations: (NoteEmbedding object) => [],
      toManyRelations: (NoteEmbedding object) => {},
      getId: (NoteEmbedding object) => object.id,
      setId: (NoteEmbedding object, int id) {
        object.id = id;
      },
      objectToFB: (NoteEmbedding object, fb.Builder fbb) {
        final noteIdOffset = fbb.writeString(object.noteId);
        final titleOffset = fbb.writeString(object.title);
        final previewOffset = object.preview == null
            ? null
            : fbb.writeString(object.preview!);
        final vectorOffset = object.vector == null
            ? null
            : fbb.writeListFloat32(object.vector!);
        final metadataOffset = object.metadata == null
            ? null
            : fbb.writeString(object.metadata!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, noteIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, previewOffset);
        fbb.addOffset(4, vectorOffset);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(6, metadataOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final noteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final previewParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final vectorParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final metadataParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = NoteEmbedding(
          noteId: noteIdParam,
          title: titleParam,
          preview: previewParam,
          vector: vectorParam,
          updatedAt: updatedAtParam,
          metadata: metadataParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    NoteLinkEntity: obx_int.EntityDefinition<NoteLinkEntity>(
      model: _entities[1],
      toOneRelations: (NoteLinkEntity object) => [],
      toManyRelations: (NoteLinkEntity object) => {},
      getId: (NoteLinkEntity object) => object.id,
      setId: (NoteLinkEntity object, int id) {
        object.id = id;
      },
      objectToFB: (NoteLinkEntity object, fb.Builder fbb) {
        final sourceNoteIdOffset = fbb.writeString(object.sourceNoteId);
        final targetNoteIdOffset = fbb.writeString(object.targetNoteId);
        final linkTypeOffset = fbb.writeString(object.linkType);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sourceNoteIdOffset);
        fbb.addOffset(2, targetNoteIdOffset);
        fbb.addOffset(3, linkTypeOffset);
        fbb.addFloat64(4, object.similarityScore);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final sourceNoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final targetNoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final linkTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final similarityScoreParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final object = NoteLinkEntity(
          sourceNoteId: sourceNoteIdParam,
          targetNoteId: targetNoteIdParam,
          linkType: linkTypeParam,
          similarityScore: similarityScoreParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    NoteTopicLink: obx_int.EntityDefinition<NoteTopicLink>(
      model: _entities[2],
      toOneRelations: (NoteTopicLink object) => [],
      toManyRelations: (NoteTopicLink object) => {},
      getId: (NoteTopicLink object) => object.id,
      setId: (NoteTopicLink object, int id) {
        object.id = id;
      },
      objectToFB: (NoteTopicLink object, fb.Builder fbb) {
        final noteIdOffset = fbb.writeString(object.noteId);
        final topicIdOffset = fbb.writeString(object.topicId);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, noteIdOffset);
        fbb.addOffset(2, topicIdOffset);
        fbb.addFloat64(3, object.weight);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final noteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final topicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final weightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = NoteTopicLink(
          noteId: noteIdParam,
          topicId: topicIdParam,
          weight: weightParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    TopicHub: obx_int.EntityDefinition<TopicHub>(
      model: _entities[3],
      toOneRelations: (TopicHub object) => [],
      toManyRelations: (TopicHub object) => {},
      getId: (TopicHub object) => object.id,
      setId: (TopicHub object, int id) {
        object.id = id;
      },
      objectToFB: (TopicHub object, fb.Builder fbb) {
        final topicIdOffset = fbb.writeString(object.topicId);
        final labelOffset = fbb.writeString(object.label);
        final colorOffset = object.color == null
            ? null
            : fbb.writeString(object.color!);
        final centroidVectorOffset = object.centroidVector == null
            ? null
            : fbb.writeListFloat32(object.centroidVector!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, topicIdOffset);
        fbb.addOffset(2, labelOffset);
        fbb.addOffset(3, colorOffset);
        fbb.addInt64(4, object.noteCount);
        fbb.addOffset(5, centroidVectorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final topicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final colorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final noteCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final centroidVectorParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = TopicHub(
          topicId: topicIdParam,
          label: labelParam,
          color: colorParam,
          noteCount: noteCountParam,
          centroidVector: centroidVectorParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NoteEmbedding] entity fields to define ObjectBox queries.
class NoteEmbedding_ {
  /// See [NoteEmbedding.id].
  static final id = obx.QueryIntegerProperty<NoteEmbedding>(
    _entities[0].properties[0],
  );

  /// See [NoteEmbedding.noteId].
  static final noteId = obx.QueryStringProperty<NoteEmbedding>(
    _entities[0].properties[1],
  );

  /// See [NoteEmbedding.title].
  static final title = obx.QueryStringProperty<NoteEmbedding>(
    _entities[0].properties[2],
  );

  /// See [NoteEmbedding.preview].
  static final preview = obx.QueryStringProperty<NoteEmbedding>(
    _entities[0].properties[3],
  );

  /// See [NoteEmbedding.vector].
  static final vector = obx.QueryHnswProperty<NoteEmbedding>(
    _entities[0].properties[4],
  );

  /// See [NoteEmbedding.updatedAt].
  static final updatedAt = obx.QueryDateProperty<NoteEmbedding>(
    _entities[0].properties[5],
  );

  /// See [NoteEmbedding.metadata].
  static final metadata = obx.QueryStringProperty<NoteEmbedding>(
    _entities[0].properties[6],
  );
}

/// [NoteLinkEntity] entity fields to define ObjectBox queries.
class NoteLinkEntity_ {
  /// See [NoteLinkEntity.id].
  static final id = obx.QueryIntegerProperty<NoteLinkEntity>(
    _entities[1].properties[0],
  );

  /// See [NoteLinkEntity.sourceNoteId].
  static final sourceNoteId = obx.QueryStringProperty<NoteLinkEntity>(
    _entities[1].properties[1],
  );

  /// See [NoteLinkEntity.targetNoteId].
  static final targetNoteId = obx.QueryStringProperty<NoteLinkEntity>(
    _entities[1].properties[2],
  );

  /// See [NoteLinkEntity.linkType].
  static final linkType = obx.QueryStringProperty<NoteLinkEntity>(
    _entities[1].properties[3],
  );

  /// See [NoteLinkEntity.similarityScore].
  static final similarityScore = obx.QueryDoubleProperty<NoteLinkEntity>(
    _entities[1].properties[4],
  );
}

/// [NoteTopicLink] entity fields to define ObjectBox queries.
class NoteTopicLink_ {
  /// See [NoteTopicLink.id].
  static final id = obx.QueryIntegerProperty<NoteTopicLink>(
    _entities[2].properties[0],
  );

  /// See [NoteTopicLink.noteId].
  static final noteId = obx.QueryStringProperty<NoteTopicLink>(
    _entities[2].properties[1],
  );

  /// See [NoteTopicLink.topicId].
  static final topicId = obx.QueryStringProperty<NoteTopicLink>(
    _entities[2].properties[2],
  );

  /// See [NoteTopicLink.weight].
  static final weight = obx.QueryDoubleProperty<NoteTopicLink>(
    _entities[2].properties[3],
  );
}

/// [TopicHub] entity fields to define ObjectBox queries.
class TopicHub_ {
  /// See [TopicHub.id].
  static final id = obx.QueryIntegerProperty<TopicHub>(
    _entities[3].properties[0],
  );

  /// See [TopicHub.topicId].
  static final topicId = obx.QueryStringProperty<TopicHub>(
    _entities[3].properties[1],
  );

  /// See [TopicHub.label].
  static final label = obx.QueryStringProperty<TopicHub>(
    _entities[3].properties[2],
  );

  /// See [TopicHub.color].
  static final color = obx.QueryStringProperty<TopicHub>(
    _entities[3].properties[3],
  );

  /// See [TopicHub.noteCount].
  static final noteCount = obx.QueryIntegerProperty<TopicHub>(
    _entities[3].properties[4],
  );

  /// See [TopicHub.centroidVector].
  static final centroidVector = obx.QueryHnswProperty<TopicHub>(
    _entities[3].properties[5],
  );
}
