// This file is automatically generated by flutter_rust_bridge
// Do not modify manually

#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

// Section: wire functions

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

// Section: impl NewWithNullPtr

// Section: sync execution mode utility

// This file will be regenerated by flutter_rust_bridge_codegen
// when generating the actual bindings.
