// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class AudioRustLibApiImplPlatform
    extends BaseApiImpl<AudioRustLibWire> {
  AudioRustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DartTranscription dco_decode_box_autoadd_dart_transcription(dynamic raw);

  @protected
  DartSynthesizedAudio dco_decode_dart_synthesized_audio(dynamic raw);

  @protected
  DartTranscription dco_decode_dart_transcription(dynamic raw);

  @protected
  DartTranscriptionSegment dco_decode_dart_transcription_segment(dynamic raw);

  @protected
  DartVadResult dco_decode_dart_vad_result(dynamic raw);

  @protected
  DartVoiceStyle dco_decode_dart_voice_style(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DartTranscriptionSegment> dco_decode_list_dart_transcription_segment(
    dynamic raw,
  );

  @protected
  List<DartVoiceStyle> dco_decode_list_dart_voice_style(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw);

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DartTranscription? dco_decode_opt_box_autoadd_dart_transcription(dynamic raw);

  @protected
  StreamingResult dco_decode_streaming_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DartTranscription sse_decode_box_autoadd_dart_transcription(
    SseDeserializer deserializer,
  );

  @protected
  DartSynthesizedAudio sse_decode_dart_synthesized_audio(
    SseDeserializer deserializer,
  );

  @protected
  DartTranscription sse_decode_dart_transcription(SseDeserializer deserializer);

  @protected
  DartTranscriptionSegment sse_decode_dart_transcription_segment(
    SseDeserializer deserializer,
  );

  @protected
  DartVadResult sse_decode_dart_vad_result(SseDeserializer deserializer);

  @protected
  DartVoiceStyle sse_decode_dart_voice_style(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DartTranscriptionSegment> sse_decode_list_dart_transcription_segment(
    SseDeserializer deserializer,
  );

  @protected
  List<DartVoiceStyle> sse_decode_list_dart_voice_style(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer);

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DartTranscription? sse_decode_opt_box_autoadd_dart_transcription(
    SseDeserializer deserializer,
  );

  @protected
  StreamingResult sse_decode_streaming_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_dart_transcription>
  cst_encode_box_autoadd_dart_transcription(DartTranscription raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_dart_transcription();
    cst_api_fill_to_wire_dart_transcription(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_dart_transcription_segment>
  cst_encode_list_dart_transcription_segment(
    List<DartTranscriptionSegment> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_dart_transcription_segment(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_dart_transcription_segment(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_dart_voice_style> cst_encode_list_dart_voice_style(
    List<DartVoiceStyle> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_dart_voice_style(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_dart_voice_style(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_f_32_loose> cst_encode_list_prim_f_32_loose(
    List<double> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_f_32_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_f_32_strict> cst_encode_list_prim_f_32_strict(
    Float32List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_f_32_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_i_16_loose> cst_encode_list_prim_i_16_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_i_16_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_i_16_strict> cst_encode_list_prim_i_16_strict(
    Int16List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_i_16_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_dart_transcription>
  cst_encode_opt_box_autoadd_dart_transcription(DartTranscription? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_dart_transcription(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_dart_transcription(
    DartTranscription apiObj,
    ffi.Pointer<wire_cst_dart_transcription> wireObj,
  ) {
    cst_api_fill_to_wire_dart_transcription(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_dart_synthesized_audio(
    DartSynthesizedAudio apiObj,
    wire_cst_dart_synthesized_audio wireObj,
  ) {
    wireObj.samples = cst_encode_list_prim_f_32_strict(apiObj.samples);
    wireObj.sample_rate = cst_encode_u_32(apiObj.sampleRate);
    wireObj.duration = cst_encode_f_32(apiObj.duration);
  }

  @protected
  void cst_api_fill_to_wire_dart_transcription(
    DartTranscription apiObj,
    wire_cst_dart_transcription wireObj,
  ) {
    wireObj.segments = cst_encode_list_dart_transcription_segment(
      apiObj.segments,
    );
    wireObj.language = cst_encode_opt_String(apiObj.language);
    wireObj.duration = cst_encode_f_32(apiObj.duration);
    wireObj.processing_time_ms = cst_encode_u_64(apiObj.processingTimeMs);
    wireObj.full_text = cst_encode_String(apiObj.fullText);
  }

  @protected
  void cst_api_fill_to_wire_dart_transcription_segment(
    DartTranscriptionSegment apiObj,
    wire_cst_dart_transcription_segment wireObj,
  ) {
    wireObj.id = cst_encode_u_32(apiObj.id);
    wireObj.text = cst_encode_String(apiObj.text);
    wireObj.start_time = cst_encode_f_32(apiObj.startTime);
    wireObj.end_time = cst_encode_f_32(apiObj.endTime);
    wireObj.language = cst_encode_opt_String(apiObj.language);
    wireObj.confidence = cst_encode_f_32(apiObj.confidence);
    wireObj.is_final = cst_encode_bool(apiObj.isFinal);
  }

  @protected
  void cst_api_fill_to_wire_dart_vad_result(
    DartVadResult apiObj,
    wire_cst_dart_vad_result wireObj,
  ) {
    wireObj.state = cst_encode_i_32(apiObj.state);
    wireObj.speech_probability = cst_encode_f_32(apiObj.speechProbability);
    wireObj.is_speech = cst_encode_bool(apiObj.isSpeech);
    wireObj.state_duration = cst_encode_f_32(apiObj.stateDuration);
  }

  @protected
  void cst_api_fill_to_wire_dart_voice_style(
    DartVoiceStyle apiObj,
    wire_cst_dart_voice_style wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.description = cst_encode_String(apiObj.description);
    wireObj.rate = cst_encode_f_32(apiObj.rate);
    wireObj.pitch = cst_encode_f_32(apiObj.pitch);
  }

  @protected
  void cst_api_fill_to_wire_streaming_result(
    StreamingResult apiObj,
    wire_cst_streaming_result wireObj,
  ) {
    cst_api_fill_to_wire_dart_vad_result(apiObj.vad, wireObj.vad);
    wireObj.transcription_attempted = cst_encode_bool(
      apiObj.transcriptionAttempted,
    );
    wireObj.transcription = cst_encode_opt_box_autoadd_dart_transcription(
      apiObj.transcription,
    );
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_16(int raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dart_transcription(
    DartTranscription self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dart_synthesized_audio(
    DartSynthesizedAudio self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dart_transcription(
    DartTranscription self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dart_transcription_segment(
    DartTranscriptionSegment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dart_vad_result(DartVadResult self, SseSerializer serializer);

  @protected
  void sse_encode_dart_voice_style(
    DartVoiceStyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dart_transcription_segment(
    List<DartTranscriptionSegment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dart_voice_style(
    List<DartVoiceStyle> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dart_transcription(
    DartTranscription? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_streaming_result(
    StreamingResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class AudioRustLibWire implements BaseWire {
  factory AudioRustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      AudioRustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AudioRustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AudioRustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  WireSyncRust2DartDco wire__crate__api__audio_buffer_available() {
    return _wire__crate__api__audio_buffer_available();
  }

  late final _wire__crate__api__audio_buffer_availablePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__audio_buffer_available',
      );
  late final _wire__crate__api__audio_buffer_available =
      _wire__crate__api__audio_buffer_availablePtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__audio_buffer_available_duration() {
    return _wire__crate__api__audio_buffer_available_duration();
  }

  late final _wire__crate__api__audio_buffer_available_durationPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__audio_buffer_available_duration',
      );
  late final _wire__crate__api__audio_buffer_available_duration =
      _wire__crate__api__audio_buffer_available_durationPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__audio_buffer_clear() {
    return _wire__crate__api__audio_buffer_clear();
  }

  late final _wire__crate__api__audio_buffer_clearPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__audio_buffer_clear',
      );
  late final _wire__crate__api__audio_buffer_clear =
      _wire__crate__api__audio_buffer_clearPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__audio_buffer_has_full_chunk() {
    return _wire__crate__api__audio_buffer_has_full_chunk();
  }

  late final _wire__crate__api__audio_buffer_has_full_chunkPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__audio_buffer_has_full_chunk',
      );
  late final _wire__crate__api__audio_buffer_has_full_chunk =
      _wire__crate__api__audio_buffer_has_full_chunkPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__audio_buffer_read(int count) {
    return _wire__crate__api__audio_buffer_read(count);
  }

  late final _wire__crate__api__audio_buffer_readPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.UintPtr)>>(
        'frbgen_kivixa_wire__crate__api__audio_buffer_read',
      );
  late final _wire__crate__api__audio_buffer_read =
      _wire__crate__api__audio_buffer_readPtr
          .asFunction<WireSyncRust2DartDco Function(int)>();

  WireSyncRust2DartDco wire__crate__api__audio_buffer_read_all() {
    return _wire__crate__api__audio_buffer_read_all();
  }

  late final _wire__crate__api__audio_buffer_read_allPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__audio_buffer_read_all',
      );
  late final _wire__crate__api__audio_buffer_read_all =
      _wire__crate__api__audio_buffer_read_allPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__audio_buffer_write_bytes(
    ffi.Pointer<wire_cst_list_prim_u_8_loose> bytes,
  ) {
    return _wire__crate__api__audio_buffer_write_bytes(bytes);
  }

  late final _wire__crate__api__audio_buffer_write_bytesPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__audio_buffer_write_bytes');
  late final _wire__crate__api__audio_buffer_write_bytes =
      _wire__crate__api__audio_buffer_write_bytesPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__audio_buffer_write_i16(
    ffi.Pointer<wire_cst_list_prim_i_16_loose> samples,
  ) {
    return _wire__crate__api__audio_buffer_write_i16(samples);
  }

  late final _wire__crate__api__audio_buffer_write_i16Ptr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_i_16_loose>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__audio_buffer_write_i16');
  late final _wire__crate__api__audio_buffer_write_i16 =
      _wire__crate__api__audio_buffer_write_i16Ptr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_i_16_loose>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__audio_buffer_write_samples(
    ffi.Pointer<wire_cst_list_prim_f_32_loose> samples,
  ) {
    return _wire__crate__api__audio_buffer_write_samples(samples);
  }

  late final _wire__crate__api__audio_buffer_write_samplesPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_f_32_loose>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__audio_buffer_write_samples');
  late final _wire__crate__api__audio_buffer_write_samples =
      _wire__crate__api__audio_buffer_write_samplesPtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_f_32_loose>,
            )
          >();

  void wire__crate__api__audio_initialize_all(int port_) {
    return _wire__crate__api__audio_initialize_all(port_);
  }

  late final _wire__crate__api__audio_initialize_allPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_kivixa_wire__crate__api__audio_initialize_all',
      );
  late final _wire__crate__api__audio_initialize_all =
      _wire__crate__api__audio_initialize_allPtr
          .asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__audio_module_health_check() {
    return _wire__crate__api__audio_module_health_check();
  }

  late final _wire__crate__api__audio_module_health_checkPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__audio_module_health_check',
      );
  late final _wire__crate__api__audio_module_health_check =
      _wire__crate__api__audio_module_health_checkPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__audio_module_version() {
    return _wire__crate__api__audio_module_version();
  }

  late final _wire__crate__api__audio_module_versionPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__audio_module_version',
      );
  late final _wire__crate__api__audio_module_version =
      _wire__crate__api__audio_module_versionPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__audio_reset_all() {
    return _wire__crate__api__audio_reset_all();
  }

  late final _wire__crate__api__audio_reset_allPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__audio_reset_all',
      );
  late final _wire__crate__api__audio_reset_all =
      _wire__crate__api__audio_reset_allPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__get_whisper_sample_rate() {
    return _wire__crate__api__get_whisper_sample_rate();
  }

  late final _wire__crate__api__get_whisper_sample_ratePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__get_whisper_sample_rate',
      );
  late final _wire__crate__api__get_whisper_sample_rate =
      _wire__crate__api__get_whisper_sample_ratePtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__process_streaming_audio(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> bytes,
    double start_time,
    bool force_transcribe,
  ) {
    return _wire__crate__api__process_streaming_audio(
      port_,
      bytes,
      start_time,
      force_transcribe,
    );
  }

  late final _wire__crate__api__process_streaming_audioPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Float,
            ffi.Bool,
          )
        >
      >('frbgen_kivixa_wire__crate__api__process_streaming_audio');
  late final _wire__crate__api__process_streaming_audio =
      _wire__crate__api__process_streaming_audioPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              double,
              bool,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__stt_available_models() {
    return _wire__crate__api__stt_available_models();
  }

  late final _wire__crate__api__stt_available_modelsPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__stt_available_models',
      );
  late final _wire__crate__api__stt_available_models =
      _wire__crate__api__stt_available_modelsPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__stt_initialize(int port_) {
    return _wire__crate__api__stt_initialize(port_);
  }

  late final _wire__crate__api__stt_initializePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_kivixa_wire__crate__api__stt_initialize',
      );
  late final _wire__crate__api__stt_initialize =
      _wire__crate__api__stt_initializePtr.asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__stt_is_ready() {
    return _wire__crate__api__stt_is_ready();
  }

  late final _wire__crate__api__stt_is_readyPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__stt_is_ready',
      );
  late final _wire__crate__api__stt_is_ready =
      _wire__crate__api__stt_is_readyPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__stt_model_size(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> model_name,
  ) {
    return _wire__crate__api__stt_model_size(model_name);
  }

  late final _wire__crate__api__stt_model_sizePtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__stt_model_size');
  late final _wire__crate__api__stt_model_size =
      _wire__crate__api__stt_model_sizePtr
          .asFunction<
            WireSyncRust2DartDco Function(
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__stt_process(
    int port_,
    ffi.Pointer<wire_cst_list_prim_f_32_loose> samples,
    double start_time,
  ) {
    return _wire__crate__api__stt_process(port_, samples, start_time);
  }

  late final _wire__crate__api__stt_processPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_f_32_loose>,
            ffi.Float,
          )
        >
      >('frbgen_kivixa_wire__crate__api__stt_process');
  late final _wire__crate__api__stt_process = _wire__crate__api__stt_processPtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_f_32_loose>, double)
      >();

  void wire__crate__api__stt_process_buffer(int port_, double start_time) {
    return _wire__crate__api__stt_process_buffer(port_, start_time);
  }

  late final _wire__crate__api__stt_process_bufferPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float)>>(
        'frbgen_kivixa_wire__crate__api__stt_process_buffer',
      );
  late final _wire__crate__api__stt_process_buffer =
      _wire__crate__api__stt_process_bufferPtr
          .asFunction<void Function(int, double)>();

  WireSyncRust2DartDco wire__crate__api__stt_reset() {
    return _wire__crate__api__stt_reset();
  }

  late final _wire__crate__api__stt_resetPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__stt_reset',
      );
  late final _wire__crate__api__stt_reset = _wire__crate__api__stt_resetPtr
      .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__stt_state() {
    return _wire__crate__api__stt_state();
  }

  late final _wire__crate__api__stt_statePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__stt_state',
      );
  late final _wire__crate__api__stt_state = _wire__crate__api__stt_statePtr
      .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__tts_available_voices() {
    return _wire__crate__api__tts_available_voices();
  }

  late final _wire__crate__api__tts_available_voicesPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__tts_available_voices',
      );
  late final _wire__crate__api__tts_available_voices =
      _wire__crate__api__tts_available_voicesPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__tts_initialize(int port_) {
    return _wire__crate__api__tts_initialize(port_);
  }

  late final _wire__crate__api__tts_initializePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_kivixa_wire__crate__api__tts_initialize',
      );
  late final _wire__crate__api__tts_initialize =
      _wire__crate__api__tts_initializePtr.asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__tts_is_ready() {
    return _wire__crate__api__tts_is_ready();
  }

  late final _wire__crate__api__tts_is_readyPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__tts_is_ready',
      );
  late final _wire__crate__api__tts_is_ready =
      _wire__crate__api__tts_is_readyPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__tts_state() {
    return _wire__crate__api__tts_state();
  }

  late final _wire__crate__api__tts_statePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__tts_state',
      );
  late final _wire__crate__api__tts_state = _wire__crate__api__tts_statePtr
      .asFunction<WireSyncRust2DartDco Function()>();

  void wire__crate__api__tts_synthesize(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
  ) {
    return _wire__crate__api__tts_synthesize(port_, text);
  }

  late final _wire__crate__api__tts_synthesizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__tts_synthesize');
  late final _wire__crate__api__tts_synthesize =
      _wire__crate__api__tts_synthesizePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__tts_synthesize_to_bytes(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
  ) {
    return _wire__crate__api__tts_synthesize_to_bytes(port_, text);
  }

  late final _wire__crate__api__tts_synthesize_to_bytesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__tts_synthesize_to_bytes');
  late final _wire__crate__api__tts_synthesize_to_bytes =
      _wire__crate__api__tts_synthesize_to_bytesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__tts_synthesize_to_i16(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
  ) {
    return _wire__crate__api__tts_synthesize_to_i16(port_, text);
  }

  late final _wire__crate__api__tts_synthesize_to_i16Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__tts_synthesize_to_i16');
  late final _wire__crate__api__tts_synthesize_to_i16 =
      _wire__crate__api__tts_synthesize_to_i16Ptr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__tts_synthesize_with_voice(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> voice_id,
  ) {
    return _wire__crate__api__tts_synthesize_with_voice(port_, text, voice_id);
  }

  late final _wire__crate__api__tts_synthesize_with_voicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__tts_synthesize_with_voice');
  late final _wire__crate__api__tts_synthesize_with_voice =
      _wire__crate__api__tts_synthesize_with_voicePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  WireSyncRust2DartDco wire__crate__api__vad_current_state() {
    return _wire__crate__api__vad_current_state();
  }

  late final _wire__crate__api__vad_current_statePtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__vad_current_state',
      );
  late final _wire__crate__api__vad_current_state =
      _wire__crate__api__vad_current_statePtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__vad_is_speech() {
    return _wire__crate__api__vad_is_speech();
  }

  late final _wire__crate__api__vad_is_speechPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__vad_is_speech',
      );
  late final _wire__crate__api__vad_is_speech =
      _wire__crate__api__vad_is_speechPtr
          .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__vad_process(
    ffi.Pointer<wire_cst_list_prim_f_32_loose> samples,
  ) {
    return _wire__crate__api__vad_process(samples);
  }

  late final _wire__crate__api__vad_processPtr =
      _lookup<
        ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_f_32_loose>,
          )
        >
      >('frbgen_kivixa_wire__crate__api__vad_process');
  late final _wire__crate__api__vad_process = _wire__crate__api__vad_processPtr
      .asFunction<
        WireSyncRust2DartDco Function(
          ffi.Pointer<wire_cst_list_prim_f_32_loose>,
        )
      >();

  WireSyncRust2DartDco wire__crate__api__vad_reset() {
    return _wire__crate__api__vad_reset();
  }

  late final _wire__crate__api__vad_resetPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function()>>(
        'frbgen_kivixa_wire__crate__api__vad_reset',
      );
  late final _wire__crate__api__vad_reset = _wire__crate__api__vad_resetPtr
      .asFunction<WireSyncRust2DartDco Function()>();

  WireSyncRust2DartDco wire__crate__api__vad_set_threshold(double threshold) {
    return _wire__crate__api__vad_set_threshold(threshold);
  }

  late final _wire__crate__api__vad_set_thresholdPtr =
      _lookup<ffi.NativeFunction<WireSyncRust2DartDco Function(ffi.Float)>>(
        'frbgen_kivixa_wire__crate__api__vad_set_threshold',
      );
  late final _wire__crate__api__vad_set_threshold =
      _wire__crate__api__vad_set_thresholdPtr
          .asFunction<WireSyncRust2DartDco Function(double)>();

  ffi.Pointer<wire_cst_dart_transcription>
  cst_new_box_autoadd_dart_transcription() {
    return _cst_new_box_autoadd_dart_transcription();
  }

  late final _cst_new_box_autoadd_dart_transcriptionPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_dart_transcription> Function()>
      >('frbgen_kivixa_cst_new_box_autoadd_dart_transcription');
  late final _cst_new_box_autoadd_dart_transcription =
      _cst_new_box_autoadd_dart_transcriptionPtr
          .asFunction<ffi.Pointer<wire_cst_dart_transcription> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_dart_transcription_segment>
  cst_new_list_dart_transcription_segment(int len) {
    return _cst_new_list_dart_transcription_segment(len);
  }

  late final _cst_new_list_dart_transcription_segmentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_dart_transcription_segment> Function(
            ffi.Int32,
          )
        >
      >('frbgen_kivixa_cst_new_list_dart_transcription_segment');
  late final _cst_new_list_dart_transcription_segment =
      _cst_new_list_dart_transcription_segmentPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_dart_transcription_segment> Function(int)
          >();

  ffi.Pointer<wire_cst_list_dart_voice_style> cst_new_list_dart_voice_style(
    int len,
  ) {
    return _cst_new_list_dart_voice_style(len);
  }

  late final _cst_new_list_dart_voice_stylePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_dart_voice_style> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_dart_voice_style');
  late final _cst_new_list_dart_voice_style = _cst_new_list_dart_voice_stylePtr
      .asFunction<ffi.Pointer<wire_cst_list_dart_voice_style> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_f_32_loose> cst_new_list_prim_f_32_loose(
    int len,
  ) {
    return _cst_new_list_prim_f_32_loose(len);
  }

  late final _cst_new_list_prim_f_32_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_f_32_loose> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_prim_f_32_loose');
  late final _cst_new_list_prim_f_32_loose = _cst_new_list_prim_f_32_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_f_32_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_f_32_strict> cst_new_list_prim_f_32_strict(
    int len,
  ) {
    return _cst_new_list_prim_f_32_strict(len);
  }

  late final _cst_new_list_prim_f_32_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_f_32_strict> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_prim_f_32_strict');
  late final _cst_new_list_prim_f_32_strict = _cst_new_list_prim_f_32_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_f_32_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_i_16_loose> cst_new_list_prim_i_16_loose(
    int len,
  ) {
    return _cst_new_list_prim_i_16_loose(len);
  }

  late final _cst_new_list_prim_i_16_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_i_16_loose> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_prim_i_16_loose');
  late final _cst_new_list_prim_i_16_loose = _cst_new_list_prim_i_16_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_i_16_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_i_16_strict> cst_new_list_prim_i_16_strict(
    int len,
  ) {
    return _cst_new_list_prim_i_16_strict(len);
  }

  late final _cst_new_list_prim_i_16_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_i_16_strict> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_prim_i_16_strict');
  late final _cst_new_list_prim_i_16_strict = _cst_new_list_prim_i_16_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_i_16_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_kivixa_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_i_16_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Int16> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_f_32_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Float> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_dart_transcription_segment extends ffi.Struct {
  @ffi.Uint32()
  external int id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text;

  @ffi.Float()
  external double start_time;

  @ffi.Float()
  external double end_time;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> language;

  @ffi.Float()
  external double confidence;

  @ffi.Bool()
  external bool is_final;
}

final class wire_cst_list_dart_transcription_segment extends ffi.Struct {
  external ffi.Pointer<wire_cst_dart_transcription_segment> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_dart_transcription extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_dart_transcription_segment> segments;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> language;

  @ffi.Float()
  external double duration;

  @ffi.Uint64()
  external int processing_time_ms;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> full_text;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_dart_voice_style extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> description;

  @ffi.Float()
  external double rate;

  @ffi.Float()
  external double pitch;
}

final class wire_cst_list_dart_voice_style extends ffi.Struct {
  external ffi.Pointer<wire_cst_dart_voice_style> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_f_32_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Float> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_i_16_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Int16> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_dart_synthesized_audio extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_f_32_strict> samples;

  @ffi.Uint32()
  external int sample_rate;

  @ffi.Float()
  external double duration;
}

final class wire_cst_dart_vad_result extends ffi.Struct {
  @ffi.Int32()
  external int state;

  @ffi.Float()
  external double speech_probability;

  @ffi.Bool()
  external bool is_speech;

  @ffi.Float()
  external double state_duration;
}

final class wire_cst_streaming_result extends ffi.Struct {
  external wire_cst_dart_vad_result vad;

  @ffi.Bool()
  external bool transcription_attempted;

  external ffi.Pointer<wire_cst_dart_transcription> transcription;
}

const double DEFAULT_BUFFER_DURATION_SECS = 30.0;

const int WHISPER_SAMPLE_RATE = 16000;
